### ISSUE TITLE
Ideas for extension

### ISSUE THREAD

**Issue by JanCaha** [tylermorganwall/rayshader#1]
First of all, I would like to congratulate you on a great package. I have been watching it since the first version and I also wrote simple wrapper package for determination of shadows with respect to "real" sun position on the sky. It might be worth considering to merge some of this functionality into your package. The enhacements in my [package](https://github.com/JanCaha/rasterShade) allow: directly use spatial data loaded as raster, estimate sun position based on date and time (possible specified by word - i.e. _noon_) and specify maximal search distance in real world units (instead of pixels).

The questions are if you would be interested in having this functionality in **rayshader** and what would be the best way to include them.

**Comment by tylermorganwall** [comment]
Great minds think alike! I actually already have a function written that interfaces with the suncalc package to do just that. Give it a lat/long and date/time, and it will automatically calculate the position of the sun for you.

It was a little too much to include with this already-massive update, so I saved it for the next.

**Comment by mosscoder** [comment]
It would also be of great value to the scientific community if there were a way to compute irradiance and insolation given date and time, or time period. Thanks for this package!

**Comment by kstierhoff** [comment]
mosscoder, not sure whether the photobiology package will do what you are requesting, but I think it would:
https://cran.r-project.org/web/packages/photobiology/index.html

**Comment by noorfatma** [comment]
Is the export to obj format supported yet.

**Comment by tylermorganwall** [comment]
I have a tutorial for calculating sun position and angle (https://github.com/tylermorganwall/MusaMasterclass) and rayshader now supports `sf` data types directly, so I'm going to close this issue
