### ISSUE TITLE
keep graph's text elements like embossed text when exported to stl model

### ISSUE THREAD

**Issue by ghost** [tylermorganwall/rayshader#102]
Hi Tyler, I would like if possible your help regarding to rayshader package, by the way a awesome package. When a produce a 3D plot and generate a stl file I would like to to keep the text in the model plot printable as high relief text (embossed text). Is this possible or do I need to implement on my own? I already tried this:

`save_3dprint("plot3d",maxwidth = 200,unit = "mm",remove_extras = F)`

**Comment by ArturLourenco** [comment]
Hi Tyler. Any news about this feature?

**Comment by tylermorganwall** [comment]
This has been added in the latest version (4751ab2665fb007719f45982d84be6f5b0b1bbb3).
