### ISSUE TITLE
How to add points in the plot_3D

### ISSUE THREAD

**Issue by zhanghaoipp** [tylermorganwall/rayshader#104]
I have use persp to plot 3D map and use points to add point label in the map to mark some place. I found rayshader make much better 3D plot but I do not know how to do if I want to mark some place as points with different color (indicate different elevation) in the map. Dould you help me about it? I just found I can add text label but not points. Thank you!

Another question can I save the 3D plot as pdf or svg?

**Comment by tylermorganwall** [comment]
You can now add points with the `render_points()` function 7052b91dd73fe9dc745f6139bcc589c65050c4ec
