### ISSUE TITLE
Error in rgl::rgl.close(): No device opened

### ISSUE THREAD

**Issue by earthdatasci** [tylermorganwall/rayshader#105]
Hello Tyler,

First of all, thank you for this tutorial: https://www.tylermw.com/a-step-by-step-guide-to-making-3d-maps-with-satellite-imagery-in-r/! It is splendid! 

When I try to reproduce the video code (the last chunk you run in the above tutorial), I receive the below error in Jupyter lab.

`Error in rgl::rgl.close(): No device opened`
`Traceback:`

`1. rgl::rgl.close()`
`2. stop("No device opened")`

Is this a general problem in Jupyter lab? I can view the stills... just not the video.

Thanks again!

David

**Comment by tylermorganwall** [comment]
Thank you! Does a separate X11 window open with the 3D model when you call `plot_3d()`?  `rgl::rgl.close()` should just close that window. If you are seeing snapshots with `render_snapshot()`, I believe one should be open. The code that generates the video is the `av`/`system()` code in the final chunk, and it saves the video to the working directory (where the images are saved).

**Comment by earthdatasci** [comment]
Thanks Tyler. A X11 window opens for the 2D renders but not the 3D video. I do have 1440 png files but no video in the working directory. Is there a way to make a video from the images or should I delete the images and rerun the code? Thanks again for your help! I can try in RStudio, I was just hoping it would work in Jupyter Lab.

**Comment by tylermorganwall** [comment]
Running `av::av_encode_video(sprintf("zionpark%d.png",seq(1,1440,by=1)), framerate = 30, output = "neonminired.mp4")` (or the listed `system()` call) is what generates the video in the working directory--are you running that code?

**Comment by tylermorganwall** [comment]
Running av::av_encode_video(sprintf("zionpark%d.png",seq(1,1440,by=1)), framerate = 30, output = "zionpark.mp4") (or the listed system() call) is what generates the video in the working directory--are you running that code?

**Comment by earthdatasci** [comment]
Sorry for the delay. Yes. Now I get a video file in the wd but the X11 window does not show the video after the code runs and I still get:
`Error in rgl::rgl.close(): No device opened`
`Traceback:`

`1. rgl::rgl.close()`
`2. stop("No device opened")`

Anyway, I am happy with the results so long as I get the video, just thought you might be interested. I will post a video on twitter once I make one. Thanks again Tyler. Great work!
