### ISSUE TITLE
render_highquality() not running in parallel

### ISSUE THREAD

**Issue by tteo** [tylermorganwall/rayshader#107]
Hi Tyler, I seem to have run into a problem with `render_highquality()`. There is no change in processor load on Windows, sometimes I get a single thread close to 100% but am unable to get all cores to work. Tried setting `parallel = TRUE` to no avail.  On macOS, the R session aborts. 

I've tried uninstalling R/RStudio, reinstalling, and compiling rayshader and rayrender from source. Also set my machine to run at stock speeds. 

Any ideas?

**Comment by tylermorganwall** [comment]
Try uninstalling and reinstalling the RcppThread package--it's the driver behind the parallel computation in rayrender.

**Comment by tylermorganwall** [comment]
Are you still encountering this issue?

**Comment by tteo** [comment]
Sorry for dropping the ball on this. I tried this, but it didn't work for `render_highquality()`. It did fix `ambient_shade()` with `multicores = TRUE`.  This makes me think it might be an issue with my machine, especially if no one else has experienced this.

**Comment by agilebean** [comment]
> Try uninstalling and reinstalling the RcppThread package--it's the driver behind the parallel computation in rayrender.

I think you meant the package `Rcpp` not `RcppThread`

**Comment by tylermorganwall** [comment]
> > Try uninstalling and reinstalling the RcppThread package--it's the driver behind the parallel computation in rayrender.
> 
> I think you meant the package `Rcpp` not `RcppThread`

No, `RcppThread` is correct. It's an extension package that enables multithreaded C++ computation with `Rcpp`.

**Comment by agilebean** [comment]
Strange, it wasn't even installed:
```
remove.packages("RcppThread")
Removing package from ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library’
(as ‘lib’ is unspecified)
Error in remove.packages : there is no package called ‘RcppThread’
```
Fortunately, installing anew worked:
```
install.packages("RcppThread")
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/RcppThread_0.5.4.tgz'
Content type 'application/x-gzip' length 310305 bytes (303 KB)
```

But: plot_gg() throws this error:

```
ggdiamonds = ggplot(diamonds, aes(x, depth)) +
  stat_density_2d(aes(fill = stat(nlevel)), geom = "polygon", n = 100, bins = 10,contour = TRUE) +
  facet_wrap(clarity~.) +
  scale_fill_viridis_c(option = "A")

plot_gg(ggdiamonds,multicore=TRUE,width=5,height=5,scale=250,windowsize=c(1400,866),
        zoom = 0.55, phi = 30)

Error in makePSOCKcluster(names = spec, ...) : 
  Cluster setup failed. 16 of 16 workers failed to connect.
```

**Comment by tylermorganwall** [comment]
@tteo Was this issue fixed when you updated `rgl`?

**Comment by tylermorganwall** [comment]
Closing (if the issue isn't resolved, we can reopen the issue, but I don't believe this is a rayshader issue anyway).

**Comment by tteo** [comment]
Yes, it's all fixed for me now! Thank you!
