### ISSUE TITLE
could not find function "plot_gg"

### ISSUE THREAD

**Issue by AoyueBi** [tylermorganwall/rayshader#108]
I wonder why you can not put a release version for this package. I can not download the rayshader_0.15.2.tar.gz.

Like this:
Error: Failed to install 'rayshader' from GitHub:
  (converted from warning) installation of package ‘/var/folders/v6/qcm7p4s16vs29lyycwcn39lh0000gp/T//RtmpxiuOWJ/file3f52645aae00/rayshader_0.15.2.tar.gz’ had non-zero exit status

**Comment by tylermorganwall** [comment]
This is a local installation problem. Try removing the package manually if it already exists in your library directory. You can then either try installing from the CRAN `install.packages("rayshader")`, or use the remotes package to install from github: `remotes::install_github("tylermorganwall/rayshader")`.
