### ISSUE TITLE
Huge memory consumption difference between 0.15.2 and 0.16 version

### ISSUE THREAD

**Issue by AnthonyGermain** [tylermorganwall/rayshader#109]
Hi Tyler, I am super excited about the new version of rayshader and I was testing it starting yesterday when I encounter big memory issues. I tried to make exhaustive testing so it will be as helpful as possible and you can find the code and screenshot here : [https://drive.google.com/open?id=1cNctPfXA385mNjMOVbZlsw_GTeC96hfe](url)

So just to sum-up my experimentation, I was running R 3.6 and rayshader 0.15.2. I upgraded to 0.16 and then faced memory issues. I then thought it could be because I didn't run R 4.0 so I upgraded to R 4.0.

I still add the issue. I then downgraded back to rayshader 0.15.2 for R3.6. So then I could switch between the two versions just by selecting R3.6 or R 4.0 in rstudio. not the best as I have 2 versions of R but practical considering I switch back and forth to run multiples test.

Starting with the easy part, I used your example code : 

> 
par(mfrow = c(1, 1))
plot_gg(pp, width = 5, height = 4, scale = 300, raytrace = FALSE, windowsize = c(1200, 960),
        fov = 70, zoom = 0.4, theta = 330, phi = 20,  max_error = 0.01, verbose = TRUE)
## 98.8% reduction: Number of triangles reduced from 3600000 to 41446. Error: 0.009996
Sys.sleep(0.2)
render_highquality(samples = 400, aperture=30, light = FALSE, ambient = TRUE,focal_distance = 1700,
                   obj_material = rayrender::dielectric(attenuation = c(1,1,0.3)/200), 
                   ground_material = rayrender::diffuse(checkercolor = "grey80",sigma=90,checkerperiod = 100))
> 

It doesn't work for me in the latest version. It produces this weird result.

![Rayshader 16 0 - from documentation example 2 bis](https://user-images.githubusercontent.com/8821989/81482688-c9f86f80-91ed-11ea-8e64-18bb404c729e.PNG)

It puzzled me so I tested with the triangle reduction on 0.15.2 vs 0.16.

I made it work on 0.15.2 (definitely slower!)

![Rayshader 15 2 - from documentation example 3](https://user-images.githubusercontent.com/8821989/81482712-f2806980-91ed-11ea-9b90-4f014ef04249.PNG)

but still the same issue on 0.16 ()

![Rayshader 16 0 - from documentation example 3](https://user-images.githubusercontent.com/8821989/81482721-04faa300-91ee-11ea-8bfe-eeb325f14b60.PNG)

**--- I'm wondering if this is related or not to the main issue which is memory.**

So my main issue, you can find all the data in the link at the beginning if you want to test it yourself, my laptop has 16GB of ram and I used to be able to run full resolution and half resolution of Ohrid (inspired by your awesome tutorial [https://t.co/os92oLm4I7?amp=1](url) )

with the new version, I cannot even run the full res, it crashed my laptop, I manage to have it crash nicely enough I could get some profiling info for you (requesting more than 32GB)
I can run the half res version but it is almost using all my available ram which looks like almost 10 times more than the old version.

half res, performance 0.15.2 : 

![Rayshader 15 2 - half res](https://user-images.githubusercontent.com/8821989/81482867-f2349e00-91ee-11ea-8929-e7e7596cf8e0.PNG)

half res, performance 0.16.0 : 

![Rayshader 16 0 - half res](https://user-images.githubusercontent.com/8821989/81482874-fcef3300-91ee-11ea-99bf-bfe69ff5ade0.PNG)

half res, performance 0.16.0 rayrender 0.10.1 : 

![Rayshader 16 0 - half res rayrender 10 1](https://user-images.githubusercontent.com/8821989/81482925-46d81900-91ef-11ea-83f7-f1f5dd790c53.PNG)

full res, performance 0.15.2 : 

![Rayshader 15 2 - full res](https://user-images.githubusercontent.com/8821989/81482902-2314d300-91ef-11ea-96b5-52c11385e43f.PNG)

full res, performance 0.16.0 (render didn't finish, crashed before), rayrender 0.10.1

![Rayshader 16 0 - full res rayrender 10 1 - crashing](https://user-images.githubusercontent.com/8821989/81482940-535c7180-91ef-11ea-8c97-a547c7546f7a.PNG)
 
PS: I updated rayrender this morning as you released it to see if it changed things, it looks like it is improving the speed but the memory issue seems to remain.

Hopefully, this will be helpful to you, I'd be happy to run more testing if necessary.

**Comment by tylermorganwall** [comment]
What are you setting for your value of `max_error` when `triangulate = TRUE` for the large memory cases? If that value is too small you'll get no benefit from triangulation, as you're just going to draw the full model with the less-memory efficient `rgl.triangles()` (instead of `rgl.surface()`).

For the first case, it looks like the image isn't being saved. What happens when you call the function `save_obj()` with a filename? Does an image of the plot appear in your working directory, along with the obj file and a mtl file?

**Comment by tylermorganwall** [comment]
What is your setting max_error when `triangulate = TRUE` for the large memory cases? If that value is too small you'll get no benefit from triangulation, as you're just going to draw the full model with the less-memory efficient `rgl.triangles()` (instead of `rgl.surface()`).

For the first case, it looks like the image isn't being saved. What happens when you call the function `save_obj()` with a filename? Does an image of the plot appear in your working directory, along with the obj file and a mtl file?

**Comment by AnthonyGermain** [comment]
I'm actually not using triangulate = TRUE but keeping the default false. I tried Triangulate = TRUE with the default max error and it literally blocked my laptop as it requires a crazy amount of ram (more than my 16Gb or even 32GB, I tried with a VM in the cloud)

So i did tried again with max.error = 2! and I managed to at least render the map, so progress :)

![Rayshader 15 2 - full res - triangulate TRUE - max error 2](https://user-images.githubusercontent.com/8821989/81485181-fddc9080-91ff-11ea-95fb-17501dd1389c.PNG)

this version still uses a lot more memory than the previous one but looks like with this setup I stay under my total ram capacity. I noticed after closing rgl, if i run gc() i free a significant amount of memory, I'm wondering if forcing calling gc() during all your different steps couldn't improve the ram situation. Just a guess.

i called save_obj and I did generate 3 files, the obj, mlt and png.

[testObj1.zip](https://github.com/tylermorganwall/rayshader/files/4604492/testObj1.zip)

still i tried again render_highquality and obtained the same black image.

**Comment by AnthonyGermain** [comment]
This may lead nowhere but triangulate seems to make things worst on a simple matrix %>% sphere_shade (at least in term of memory).

without triangulate : 

![sphere shade triangulate False](https://user-images.githubusercontent.com/8821989/81485695-046d0700-9204-11ea-9fa6-9ccbf4bccd39.PNG)

![sphere shade triangulate False - profile](https://user-images.githubusercontent.com/8821989/81485696-0767f780-9204-11ea-862b-9162c5dd7f89.PNG)

with triangulate, amx error 2 : 

![sphere shade max error 2](https://user-images.githubusercontent.com/8821989/81485704-1353b980-9204-11ea-992d-f6399d3fa34d.PNG)

![sphere shade max error 2 - profile](https://user-images.githubusercontent.com/8821989/81485705-164eaa00-9204-11ea-9586-c5835c494c50.PNG)

**Comment by AnthonyGermain** [comment]
using max.error 2 and above produces incredible results, I would put the default value of max error maybe higher or people using large matrix should just be careful. 

the dielectric effect is not solved unfortunately. I'll continue testing :)

**Comment by tylermorganwall** [comment]
If `triangulate = FALSE`, `plot_3d()` should use the same amount of memory it used in 0.15.2, since it defaults to the prior behavior. I do see the increase in memory use you're referring to on my system when `triangulate = TRUE`, but that's expected since the triangulating process itself is memory intensive, and passing individual triangles to `rgl.triangle()` uses more memory than passing a surface via `rgl.surface()`. Most of that memory use is temporary, however--the garbage collector should automatically release those objects once they aren't needed and the R session needs more to allocate memory. Generally, you never need to call gc() manually when programming in R.

For the default for max error, the best setting for `max_error` is entirely data dependent--no default will work for all datasets. I'd just recommend playing with `max_error` until you find a value that works for your data.

I downloaded your obj file and it loaded fine--try setting the `cache_filename` argument to save the obj file in your working directory and see if it works then.

**Comment by AnthonyGermain** [comment]
Yeah that's my whole questioning because I wasn't using triangulate at first so I was expecting the same behavior than the previous version. Could you tell me how you ran it with my obj file, I did try to set up the cache_filename argument and i could see the obj created, (around 8Mb) but still the rendering failed and gave my the same kind of dark image.

![example documentation saving temp obj](https://user-images.githubusercontent.com/8821989/81509273-3f337580-92be-11ea-9731-a6c9d3d68ebf.PNG)

**Comment by tylermorganwall** [comment]
I tested it using rayrender. What do you get when you run the following code? Replace the path with your local directory. I get the following:

```r

library(rayrender)

generate_ground() %>%
  add_object(obj_model("path/to/testObj1/testObject.obj", texture = TRUE,scale_obj = 1/400)) %>%
  render_scene(lookfrom = c(0,10,10))

```
![Rplot](https://user-images.githubusercontent.com/297609/81509988-a4965f00-92dc-11ea-9add-58f7cb3b6904.png)

**Comment by AnthonyGermain** [comment]
I don't get an output when I run this, I get this : 

![rayrender bug](https://user-images.githubusercontent.com/8821989/81510909-3ea0dc00-92ca-11ea-85d7-a144a2ad47ac.PNG)

I am running the latest version, I tried reinstalling it and also with the older version 0.10.

**Comment by AnthonyGermain** [comment]
In case it helps, I played with your neon example in the past with rayrender, and testing it again right now this seems still to be fine.

![neon-example](https://user-images.githubusercontent.com/8821989/81511004-051ca080-92cb-11ea-90e1-18c752ec965e.PNG)

the issue is quite puzzling.

**Comment by tylermorganwall** [comment]
Can you uninstall rayrender (`remove.packages("rayrender")`), confirm it is uninstalled by checking the directory (or directories) listed when you call the function `.libPaths()`, and then reinstall it from github and try again?

**Comment by AnthonyGermain** [comment]
I got the same result, I actually deleted the folder the other times I reinstalled it. This time I did the remove package and the only file that remained was the rayrender.dll. 

My full session : 

[rayrendersession.txt](https://github.com/tylermorganwall/rayshader/files/4607097/rayrendersession.txt)

**Comment by tylermorganwall** [comment]
Everything looks good in that compilation log--not sure what's going on in your installation. Whenever I've seen model corrupted like you've shown, it's been due to a faulty install or incomplete uninstall (definitely remove the dll file if it's still around). Particularly on Windows, where I often have to resort to manual cleaning to fully remove the package.

Sorry I can't be of more help!

**Comment by tylermorganwall** [comment]
If you aren't able to figure this out, the next version I upload to the CRAN will have these features and I'm fairly positive the pre-compiled binary they supply won't have these issues.

**Comment by AnthonyGermain** [comment]
Hopefully it does, I actually tried again completely erasing the folder and i got the same result. I also tried by installing the binary version of cran (0.9.1) Maybe it was expected that it wouldn't work with this old version but I got the same result. Weirdly the high rendering works, it seems to be situated with this dielectric material.

![rayrender bug2](https://user-images.githubusercontent.com/8821989/81636406-a63d5100-93c8-11ea-8856-96a54bbe8833.PNG)

**Comment by tylermorganwall** [comment]
What you're seeing isn't any type of material--it's the result of NaNs encountered during pathtracing. Have you ever set any custom options for compilation? You are compiling with SSE extensions enabled `-mfpmath=sse -msse2` and with `-mstackrealign`, which aren't specified by rayrender and may be the source of your problems. I just have `-mtune=generic` on my Windows 10 system where those options would be.

**Comment by AnthonyGermain** [comment]
I didn't set any custom options for compilation, do you know how I could change those options ?

**Comment by tylermorganwall** [comment]
Check the Makeconf file (should be located in `${R_HOME}/etc/Makeconf`, type `$R_HOME` in R studios Terminal to see where that is) and remove those arguments from the CXX11* rows and see if it compiles without it.

**Comment by AnthonyGermain** [comment]
So i tried removing the options, then resinstalled rayrender. It Failed.

[session2.txt](https://github.com/tylermorganwall/rayshader/files/4618202/session2.txt)

![rayrender session 2](https://user-images.githubusercontent.com/8821989/81740235-7c7c3c80-9451-11ea-9f8d-1845db68495e.PNG)

I then tried adding your -mtune=generic option. It failed too.

[session3.txt](https://github.com/tylermorganwall/rayshader/files/4618204/session3.txt)

![rayrender session 3](https://user-images.githubusercontent.com/8821989/81740284-93229380-9451-11ea-8ee7-d0a3ba11c3d8.PNG)

my i386 Makeconf file : 


[Makeconf.txt](https://github.com/tylermorganwall/rayshader/files/4618206/Makeconf.txt)

My x64 MakeConf File : 

[Makeconf.txt](https://github.com/tylermorganwall/rayshader/files/4618211/Makeconf.txt)

Weirdly I wanted to see if with ubuntu it would go better, I was testing using ggcloud to speed up some high_quality rendering but it wasn't as fast as expected. I have the same bug under ubuntu, which is weird.

[session 4 linux.txt](https://github.com/tylermorganwall/rayshader/files/4618218/session.4.linux.txt)

![rayrender session 4 linux](https://user-images.githubusercontent.com/8821989/81740542-fa404800-9451-11ea-80ba-feff9169fd2a.PNG)

**Comment by tylermorganwall** [comment]
@AnthonyGermain Are you still having these issues with the latest version of rayshader?

**Comment by AnthonyGermain** [comment]
Hey Tyler, we can close it, I tested the latest version and the example is running fine, I'm able to get the dielectric example running.
