### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Captaineight** [tylermorganwall/rayshader#11]
Sorry for the naive question, I'm totally new in R. When I'm installing the rayshader, I got wrong here:
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/HAT_PI~1/AppData/Local/Temp/RtmpeiqxaI/file18bc520a116c/rayshader_0.5.1.tar.gz’ had non-zero exit status

Did I do anything wrong? Thank you!

**Comment by tylermorganwall** [comment]
Did you install from GitHub, or from the CRAN? I.e.,

install.packages(“rayshader”)

Or:

devtools::install_github(“tylermorganwall/rayshader”)

**Comment by Captaineight** [comment]
> Did you install from GitHub, or from the CRAN? I.e.,
> 
> install.packages(“rayshader”)
> 
> Or:
> 
> devtools::install_github(“tylermorganwall/rayshader”)

I solved the problem, it seems like I forgot one other package installed. Thank you.
