### ISSUE TITLE
How to animate the scene using time-series satellite imagery?

### ISSUE THREAD

**Issue by GokulGeo** [tylermorganwall/rayshader#111]
I have this script from this [website](https://labo.obs-mip.fr/multitemp/khumbu-icefall-in-4d/)

``
library(rayshader)
library(abind)
library(raster)
p="./"
fdem=paste0(p,"HMA_DEM8m_MOS_20170716_tile-677_UTM45_filled_crop_Venus.tif")
pimg=paste0(p,"/VIS1C/")
dem=raster(fdem)
elmat=matrix(extract(dem, extent(dem), buffer = 1000),nrow = ncol(dem), ncol = nrow(dem))
files=list.files(path=pimg, pattern="jpg$", full.names=FALSE, recursive=FALSE)

#rotating view  
th=200
k=0
for (x in files) {
    fimg=paste0(pimg,x)
    fout=paste0(p,"/3Drot/",x)
    print(x)
    txt=substr(x, 36, 43)
    k=k+1
    if (k<length(files)/2){
    th=th+0.5
    }else{
    th=th-0.5
    }
    imgr = raster(fimg,band=1)
    imgg = raster(fimg,band=2)
    imgb = raster(fimg,band=3)
    r = t(matrix(extract(imgr, extent(imgr), buffer = 1000),nrow = ncol(imgr), ncol = nrow(imgr)))
    g = t(matrix(extract(imgg, extent(imgr), buffer = 1000),nrow = ncol(imgr), ncol = nrow(imgr)))
    b = t(matrix(extract(imgb, extent(imgr), buffer = 1000),nrow = ncol(imgr), ncol = nrow(imgr)))
    col=abind(r,g,b,along=3)/255
    plot_3d(col, elmat, zscale = 5, fov = 0, theta = th, zoom = 0.7, phi = 45, windowsize = c(1000, 800))
    render_snapshot(fout,clear = TRUE,title_text = txt, title_color = "black",
               title_font = "Arial", gravity = "NorthEast", title_offset = c(0,0))
    }
``
I want to create similar animation using the images downloaded from sentinel hub
The files are arranged as,
**Satellite images**
![2020-05-16_12h38_41](https://user-images.githubusercontent.com/47848489/82113230-1a357b80-9772-11ea-9544-9e3f56f5a6f5.png)

**Digital elevation Model**
![2020-05-16_12h40_38](https://user-images.githubusercontent.com/47848489/82113266-608ada80-9772-11ea-9df5-40b6e81ee4b5.png)

How do  I replace the images and dem with my current files? I am posting this here because I didn't see any examples which are matching my requirement. Kindly suggest modification

**Comment by tylermorganwall** [comment]
You can create a `for` loop which will load each image into `fimg` and then run the rest of the script. When you have your 3D model open, take a snapshot, clear or close the rgl window (using `rgl::rgl.clear()`) and then move on to the next image. You can create an animation out of these frames using the `av` package.
