### ISSUE TITLE
RGL device is not working with plot_gg

### ISSUE THREAD

**Issue by rvaldebenito** [tylermorganwall/rayshader#114]
Hello,

First of all, thanks for the awesome package. The examples look great!
I have been trying to use rayshader and plot_gg for a while. I run the examples from the website and I can run the plot_3d of Monterey Bay without any problems. However, when it comes to plot_gg, I am not able to use it. The RGL device opens, but it does not show anything and my R session is aborted. 

I re-installed RGL and Rayshader several times and I can't fix the problem. 

I tried to run this example from the website:

`library(rayshader)`
`library(ggplot2)`
`library(rgl)`

`ggdiamonds = ggplot(diamonds) +
  stat_density_2d(aes(x = x, y = depth, fill = stat(nlevel)), 
                  geom = "polygon", n = 100, bins = 10, contour = TRUE) +
  facet_wrap(clarity~.) +
  scale_fill_viridis_c(option = "A")`
`par(mfrow = c(1, 2))`

`plot_gg(ggdiamonds, width = 5, height = 5, raytrace = FALSE, preview = TRUE)`
`plot_gg(ggdiamonds, width = 5, height = 5, multicore = TRUE, scale = 250, 
        zoom = 0.7, theta = 10, phi = 30, windowsize = c(800, 800))`

`Sys.sleep(0.2)`
`render_snapshot(clear = TRUE)`

Does anyone know how to fix the problem?
Any help is more than welcome 

Rocio

**Comment by rvaldebenito** [comment]
I tried to run the same code in R 3.6 and it did not work. I am not sure what is the problem. In my case, I tried a new example and RGL device opens a graph, but I cannot move it and if I close it, R session is aborted.

**Comment by tylermorganwall** [comment]
Are you still having this issue?

**Comment by tylermorganwall** [comment]
I don't believe this is a rayshader-specific issue, closing. If you are still having issues, you can post here.
