### ISSUE TITLE
Setting render_path() extent from raster

### ISSUE THREAD

**Issue by Ocirne94** [tylermorganwall/rayshader#115]
Hi, thanks for the great work.
I have been testing the new `render_path()` function together with a raster DEM. I am trying to set the extent parameter from the DEM (i.e. `extent = extent(dem)`), but it looks like this is the wrong extent to pass to the function (the path is not shown at the right position).
How can I compute the correct extent to pass to the function? The `raster_to_matrix()` output does not have an extent attribute.

Edit: more findings. The DEM I am using has a 1.299674 aspect ratio. Using `extent = extent(dem)*c(1.299674,1/1.299674)` puts the path to the right place (but simply transposing obviously does not - since the elevation itself changes in that case). So it looks like there might be an X-Y mismatch somewhere in the code?

**Comment by Ocirne94** [comment]
[path_extent.zip](https://github.com/tylermorganwall/rayshader/files/4799422/path_extent.zip)
Here the files of my example. To load the track:
library(rgdal)
track <- readOGR("track.gpx", layer = "tracks")
crs_21781 <- CRS("+proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 +k_0=1 +x_0=600000 +y_0=200000 +ellps=bessel +towgs84=674.4,15.1,405.3,0,0,0,0 +units=m +no_defs")
track_proj <- spTransform(track, crs_21781)
track_proj_coords <- track_proj@lines[[1]]@Lines[[1]]@coords

**Comment by tylermorganwall** [comment]
Thanks for the report! I fixed this in the latest update (900628d5b4f52505d2f4fcc018b2cb48fdc9e9ac).
![fixed](https://user-images.githubusercontent.com/297609/85492554-5941c280-b5a3-11ea-990d-c6f95bb5d9ec.png)

**Comment by hbermeo** [comment]
Why doesn't the render_path () function appear in the library?

**Comment by hbermeo** [comment]
> Why doesn't the render_path () function appear in the library?

Sorry. It had a previous version and apparently it gave me an error when installing rayshader from github, I had to use the file that is downloaded * .tr.gz to be able to install it manually. And now it works.
