### ISSUE TITLE
color paramater of add_water does not accept hexcode

### ISSUE THREAD

**Issue by ozjimbob** [tylermorganwall/rayshader#12]
Help file for add_water says you can provide a " A hexcode or recognized color string." but this doesn't seem to work, returns error:

Error in color[i]/256 : non-numeric argument to binary operator.

Looking at the function, it appears it assigns a rgb to the variable color if you provide one of the palette names, but it doesn't check if you just provide a hexcode.

**Comment by tylermorganwall** [comment]
Thanks! I had already fixed this in the developmental version, but hadn't uploaded it yet. I just uploaded the patched version with the fix.
