### ISSUE TITLE
Render Not Showing When 3D Plotting 

### ISSUE THREAD

**Issue by BigBallerBenzie** [tylermorganwall/rayshader#121]
I am running into issues getting the plot 3D to give me anything other than this empty popup when I run the code. 
I have had other data work with similar code. 
This is a pretty massive file (around 16gb) and I have 64gb ram on my system. 

My Code is here:
https://github.com/BigBallerBenzie/Earth-Engine-Piikni/blob/master/R%20Code%20Piikni
![7xn4oatwpib51](https://user-images.githubusercontent.com/58898437/87841823-d9d7a400-c86d-11ea-8d0f-9b30b4ba175b.png)

**Comment by tylermorganwall** [comment]
That may be too large for your graphics card (used by rgl), or there might be a bottleneck in rgl with that much data (that's quite a large raster). Try reducing the resolution of your data with resize_matrix() or rayimage::render_resized().

**Comment by BigBallerBenzie** [comment]
Do you know why I would be getting this error:
Error in resize_matrix(wmfr_rgb_array, scale = 0.5) : 
  could not find function "resize_matrix

Rayshader is installed

**Comment by tylermorganwall** [comment]
Install the latest version from github:

```
install.packages("remotes")
remotes::install_github("tylermorganwall/rayshader")
```

**Comment by BigBallerBenzie** [comment]
Tyler, 
I very much appreciate all of the help. I can not seem to resize any of my files. I get this error after trying to resize my matrix: 
`wmfr_rgb_array[,,1] = wmfr_r_cropped/255 #Red layer
 >wmfr_rgb_array[,,2] = wmfr_g_cropped/255 #Blue layer
>wmfr_rgb_array[,,3] = wmfr_b_cropped/255 #Green layer
> 
> wmfr_rgb_array = aperm(wmfr_rgb_array, c(2,1,3))
> plot_map(wmfr_rgb_array)
> 
> wmfr_rgb_small = resize_matrix(wmfr_rgb_array, scale=0.5)
**Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'raster': argument is not a matrix**
> wmfr_rgb_array %>%
>plot_map(wmfr_rgb_small)
**Error in temp[2:(nrow(temp) - 1), 2:(ncol(temp) - 1)] <- heightmap : 
  number of items to replace is not a multiple of replacement length**`

**Comment by BigBallerBenzie** [comment]
Update: definitely an issue with the total data, but not sure what would fix it. Renting a remote server with 256 gb ram and 10X 1080Ti I ran into the same issue. Possible it is a limitation with Rgl?

**Comment by tylermorganwall** [comment]
I would believe that this is a limitation with rgl--I don't think it was designed to handle that amount of data.

**Comment by BigBallerBenzie** [comment]
Sounds good, thank you for your help. I will have to settle for 2 halves of my area.
