### ISSUE TITLE
Strange behaviour on ggplot for bivariate maps

### ISSUE THREAD

**Issue by arielfuentes** [tylermorganwall/rayshader#124]
The panel and text axis shows an undesired output when I take the ggplot2 rayshader, I think there are extra parameters that I should set on ggplot2 that it can work properly.

`
#libraries
library(sf)
library(biscale)
library(ggplot2)
library(cowplot)
library(rayshader)

#read shapefile
nc = st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)

#create bi_class
df <- bi_class(.data = nc, x = SID74, y = SID79,  
         style = "quantile", dim = 3) %>% #set bivariate class
  na.omit()

map <- ggplot() +
  geom_sf(data = df, mapping = aes(fill = bi_class), 
          color = "black", size = 0.1, show.legend = FALSE) +
  bi_scale_fill(pal = "DkViolet", dim = 3) +
  labs(title = "title",
       subtitle = "subtitle") 

legend <- bi_legend(pal = "DkViolet",
                    dim = 3,
                    xlab = "SID74",
                    ylab = "SID79",
                    size = 8)

plotf <- cowplot::ggdraw() +
  draw_plot(map, 0, 0, 0.8, 1) +
  draw_plot(legend, 0.76, 0.2, 0.3, 0.1, scale = 2.5)

plot_gg(plotf, multicore = TRUE, width = 6 ,height=2.7, fov = 70)
render_depth(focallength=100,focus=0.72)
`

**Comment by tylermorganwall** [comment]
The panel and axis text shouldn't be an issue now in commit ba3a3b960f785cd4d635ad120b314863c124bf5c, but bivariate maps aren't really a good match for 3D: it's mapping two variables to color rather than one, so there isn't a straightforward way to convert it to 3D.
