### ISSUE TITLE
GL/glu.h is missing

### ISSUE THREAD

**Issue by hg2581** [tylermorganwall/rayshader#126]
CentOS 7 running R 3.6. Just downloaded rayshader from CRAN and was very excited to test it. However, installation fails on GL/flu.h missing.

Should it have been part of the CRAN library or is something else required for installation?

**Comment by tylermorganwall** [comment]
This is an `rgl` issue—it sounds like you are missing some required libraries on your system for that package. See the following GH issue for further discussion:

https://stackoverflow.com/questions/15292905/how-to-solve-the-error-missing-required-header-gl-gl-h-while-installing-the-p
