### ISSUE TITLE
Height computed from a dataframe (not colour nor fill)

### ISSUE THREAD

**Issue by yazun** [tylermorganwall/rayshader#128]
Would it be hard to do?

We would like to have colours on a 3D density diagram (HR diagram in astronomy).

Thanks

**Comment by tylermorganwall** [comment]
Can you provide a minimally reproducible code example of what you want to do?

**Comment by yazun** [comment]
i.e. 
bit difficult as the functionality does not exist, so maybe by a example would be easier:

Say we have 3 values: x,y,fn(y) where in our case fn(y)<- y

```r
 head(selection)
     g_rp gmag_abs
1   1.3268232  12.41924
2  1.3268232  12.6484
...
```

We have a data that has some 3D shape derived from density:


```r

# density plot
density<-ggplot(selection) +
  theme_black() +
  ggtitle("Hertzsprung-Russell diagram") +
 stat_density_2d_filled(aes(y = gmag_abs, x = g_rp,   fill=(..density..), color = "g_rp"), n=256, geom = "raster", contour = FALSE, contour_var = "density",size=1, alpha = 5/6 ) +
 scale_x_continuous(expand=c(0,0)) +
 scale_y_continuous(expand=c(0,0)) +
 scale_y_reverse() +
 scale_fill_gradient(low="lightblue", high="red") 


plot_gg(density, width = 5, height = 4, scale = 250, multicore = TRUE, raytrace=TRUE, windowsize = c(1920, 1800),
        fov = 70, zoom = 0.7, theta = 330, phi = 40        
        ,pointcontract = .6)
```
Rendering density
<img width="1439" alt="Screenshot 2020-11-26 at 16 09 48" src="https://user-images.githubusercontent.com/848285/100367145-124c7300-3002-11eb-9617-d5a838857bd7.png">

<img width="1866" alt="Screenshot 2020-11-26 at 16 07 23" src="https://user-images.githubusercontent.com/848285/100367134-0e205580-3002-11eb-860f-0b29fd585572.png">

But what we really need is 3D shape coloured not by a density but another value, temperature in this case (x-axis value in this particular case - which is temperature of a star).

Obviously we cannot use it as it will render something like this:

<img width="1862" alt="Screenshot 2020-11-26 at 16 20 20" src="https://user-images.githubusercontent.com/848285/100367989-4f653500-3003-11eb-9702-b13236429a8d.png">

So the goal is to have 3D density with colour projected on it from another variable, shape of Img 2 with colours of Img3.

Hope it is clearer now.

**Comment by tylermorganwall** [comment]
You can do this by passing a list of two ggplots to plot_gg() and one will be used to map the surface to 3D, while the other will be used to texture the surface.

e.g. 

```r
plot_gg(ggobj = list(gg1, gg2), ...)
```

**Comment by yazun** [comment]
Fantastic!
Thanks a lot! Will try shortly!

**Comment by yazun** [comment]
Works, thanks a lot! 
it is 
```r
ggobj = list(texture,surface)
```
