### ISSUE TITLE
Cloud of points in 3D

### ISSUE THREAD

**Issue by llrs** [tylermorganwall/rayshader#129]
Hi Tyler!

First time trying the package. I thought it would come handy for a problem I have: 
There are three parameters (x, y, z) that influence a 4th (w).
I thought I could use ggplot2 with rayshader to plot them in a 3D mesh and colour the points according to w. Then visualize if there is any pattern on there.

But the points are displayed as columns (aside from the warning `Ignoring unknown aesthetics: z`, which probably I should define a specific geom for this)
Is there any way the points can be represented as floating around?

Some toy code:

```
library("dplyr")
library("ggplot2")
library("rayshader")
df <- data.frame(x = runif(25), y = runif(25), z = runif(25)) %>%
      rowwise() %>% mutate(w = median(max(x, y), z))
p1 <- ggplot(df) + geom_point(aes(x = x, y = y, z = z, col = w))
plot_gg(p1)
```

Many thanks for all the amazing work you do on rayshader and related packages!

**Comment by tylermorganwall** [comment]
Thanks! Floating points aren't supported with the plot_gg() function. If you want to color the points differently than the elevation, pass in a list of two ggplots to plot_gg(): one will be used to color the surface, and the other will control the elevation mapping. You can then map all four of your variables using this method.
