### ISSUE TITLE
Specify depth of 'plinth' for plot_gg

### ISSUE THREAD

**Issue by theosanderson** [tylermorganwall/rayshader#130]
The depth of the plinth on which the graph sits seems to be determined by the maximum height of the data (?). This leads to slightly weird results when animating a series of frames (e.g. compare early and late frames in https://twitter.com/theosanderson/status/1322626834878652418). Would it be possible to allow this value to be fixed? Sorry if this feature already exists, or if the change in depth is due to a bug in my code.

**Comment by theosanderson** [comment]
(This was with render_highquality)

**Comment by tylermorganwall** [comment]
The base depth is automatically computed if you don't specify one ahead of time. You can fix the depth of the base by setting the `soliddepth` argument in `plot_gg()`, which forwards that argument to `plot_3d()`.

**Comment by theosanderson** [comment]
Thanks! Didn't think to check for pass-through arguments

**Comment by theosanderson** [comment]
Similarly I seem to find that if there is a higher maximum height on the graph the y=0 plane sinks further down in the camera. I have a fixed camera and lookat position. Is there any way I can avoid this?
