### ISSUE TITLE
Include colors when saving 3d object

### ISSUE THREAD

**Issue by Bart6114** [tylermorganwall/rayshader#132]
Is there anyway to include the color info (coming from an image overlay) into the final saved model? From my experiments both the `save_3dprint()` and `save_obj()` do not save any color info, is this correct? Is there an alternative approach to this?

My objective is to 3D print in color. I can potentially save the `.obj` and just supply a separate texture map to the printing service, but ideally I'd like to include the color info in the model itself.

**Comment by tylermorganwall** [comment]
`save_obj()` does indeed save the texture information, but it's not vertex colors—it's an image referenced in the accompanying MTL file.

If you're interested in 3D printing the object, that isn't currently possible with the standard STL format, which does not support color.
