### ISSUE TITLE
Lost sphere_shade Texture setting after using add_overlay

### ISSUE THREAD

**Issue by DrRoad** [tylermorganwall/rayshader#133]
Hi, appreciate if you can have a look at why the texture of 3D model is missing after I apply an overlay. Below is my code:

data %>%
  sphere_shade(texture = "desert",zscale = 0.1) %>%
  
  add_shadow(ray_shade(data, zscale = 0.1), 0.5) %>%

  add_overlay(height_shade(data2, texture = topo.colors(256))) %>%
  
  plot_3d(data, zscale = 0.1, fov = 0, theta = 135, zoom = 0.75, phi = 45, windowsize = c(1000, 800),background = "#F2E1D0", shadowcolor = "#523E2B")

render_highquality(lightdirection = c(-45,45), lightaltitude  = 30)
![2020-11-19_145305](https://user-images.githubusercontent.com/8111532/99611011-bde04b00-2a77-11eb-96df-d9b11723112a.png)

**Comment by tylermorganwall** [comment]
What is `data2`? It looks like you're using a different data source for the overlay than for the rest of the map.
