### ISSUE TITLE
3D Print 3D GGPlot

### ISSUE THREAD

**Issue by BigBallerBenzie** [tylermorganwall/rayshader#137]
Is there any way to 3D print a 3d density plot? I created a spectrogram and converted it to a density plot which I turned 3d using plot_gg. Is there any way to save that as an STL like you can with plot_3d?

**Comment by carywreams** [comment]
@BigBallerBenzie ,

Think these will get you closer.

+ [rstudio::conf 2019 video](https://www.youtube.com/watch?v=sB8CYGlPN0o&t=1081s)
+ [TMW Web Site Discussion](https://www.tylermw.com/3d-printing-rayshader/)
