### ISSUE TITLE
ggplot theme_void misaligns plotted data and colorbar, 

### ISSUE THREAD

**Issue by vulpescz** [tylermorganwall/rayshader#140]
Hi, the package is really cool! I came across a couple of issues when trying to plot some data on a background map though. 

1. Removing axis titles, text and ticks misaligns the plotted data and color on the colorbar.
2. Labels and other features (roads) on background maps (e.g. from ggmap) are also plotted 3D. Is there a way for the map to remain 2D?

**Comment by tylermorganwall** [comment]
This should be fixed in ba3a3b960f785cd4d635ad120b314863c124bf5c.
