### ISSUE TITLE
User-defined camera position for flight path animation?

### ISSUE THREAD

**Issue by joheisig** [tylermorganwall/rayshader#141]
Thank you Tyler for the great work you put in this package!

Let's say I have a 3D plot of a mountainous area and render a path on top of the surface. With `render_camera()` I can now loop through view angles and zoom levels to animate e.g. a rotating plot. However, the center of my view always stays the same. I would now like to follow the path so that each frame of my animation is shot from a different position along the path. The result is a video in which the viewer flies along the path in a first person view. Similar animations can be achieved with Google Earth Pro as far as I know. 
Am I missing something or is this not (yet) possible with `rayshader`?

Jo

**Comment by tylermorganwall** [comment]
You can now define a camera position/orientation via the `camera_location` and `camera_lookat` arguments in `render_snapshot()`, when `software_render = TRUE`.
