### ISSUE TITLE
rayshader error msg

### ISSUE THREAD

**Issue by ms1948** [tylermorganwall/rayshader#142]
Hi, if I  run the rayshader examples  published in https://www.rayshader.com regarding the volcano and mtcars data, I receive the following error msg for both examples:

**Error in makePSOCKcluster(names = spec, ...) : 
  Cluster setup failed. 4 of 4 workers failed to connect.**

**Comment by ms1948** [comment]
the erros show up if I use MacOS, all is ok if I use Ubuntu

**Comment by tylermorganwall** [comment]
Are you using RStudio? See the following issue/solution:

https://github.com/rstudio/rstudio/issues/6692

Update to the latest version of RStudio or use the workaround in the post.
