### ISSUE TITLE
Rayshader for bathymetry data

### ISSUE THREAD

**Issue by m4rkus84** [tylermorganwall/rayshader#143]
Hi, I would like to use rayshader to render some bathymetry data (all cells have negative values) but it seems that's is not well interpreted by the package
![image](https://user-images.githubusercontent.com/12136303/106012937-3db01480-60bc-11eb-9c42-a32dea927ccb.png)
I have noticed also a problem with rasters containing NA values

**Comment by tylermorganwall** [comment]
You will have to provide a reproducible example for your problems for me to help. I don't have any issues plotting pure bathymetry data nor have I had problems with NA values, so it's likely just an issue setting up your plot.

One issue that I can see from just the image is that it appears you're plotting two datasets without clearing the RGL device between. You can draw the water in 3D by setting `water=TRUE` in the `plot_3d()` call.

**Comment by tylermorganwall** [comment]
Feel free to post in this thread if you're still having issues (including code)—I will close this issue in the meantime unless the updates indicate a bug.
