### ISSUE TITLE
Plotting lines using render_path()

### ISSUE THREAD

**Issue by psychemedia** [tylermorganwall/rayshader#144]
My understanding of the docs to `render_path()` suggests that you should be able to pass something like `render_path(extent, lat, long)` with null defaults on the altitude and the heightmap and the path should then be rendered `offset` above the terrain.

```
#'@param altitude Default `NULL`. Elevation of each point, in units of the elevation matrix (scaled by zscale).
#'If left `NULL`, this will be just the elevation value at ths surface, offset by `offset`.
#'@param heightmap Default `NULL`. Automatically extracted from the rgl window--only use if auto-extraction
#'of matrix extent isn't working. A two-dimensional matrix, where each entry in the matrix is the elevation at that point.
#' All points are assumed to be evenly spaced.
```
Trying to run this reports `No altitude data requires heightmap argument be passed` as per https://github.com/tylermorganwall/rayshader/blob/d0c9bd94be95c44eff6e7d8da5eadff070dc11db/R/render_path.R#L133 .

**Comment by tylermorganwall** [comment]
If you're not specifying an altitude, you need to pass the heightmap as well so the function knows the terrain over which to draw the line.

```r
render_path(extent, lat, long, heightmap = your_height_map)
```

**Comment by psychemedia** [comment]
Thanks.... I think I was using rgl at the time and expected things to be handled? Or maybe by that point I was using an htmlwidget which perhaps didn't support the auto-heightmap extraction the docs hinted at?

**Comment by tylermorganwall** [comment]
Auto-extraction is specifically only for the matrix extent, so I've updated the docs to make it more clear.
