### ISSUE TITLE
Stripes in image

### ISSUE THREAD

**Issue by eeholmes** [tylermorganwall/rayshader#145]
Hi,

I am trying to use your package for the Alaska archipelago but am getting odd stripes across the water. 

```
BB <- raster::extent(-160, -155, 55, 60)
USAelevation <- raster::getData("alt", country = "USA", mask=FALSE)
BB.elevation <- raster::crop(USAelevation[[2]], BB)
library(rayshader)
elmat = raster_to_matrix(BB.elevation)
elmat %>%
  sphere_shade(texture = "desert") %>%
  add_water(detect_water(elmat), color = "desert") %>%
  plot_map()
```

I can't figure what I am doing wrong.

Thanks!

Eli
![stripes](https://user-images.githubusercontent.com/2545978/106403637-84677c80-63e4-11eb-9fd2-a707658147f2.png)

**Comment by eeholmes** [comment]
Perhaps it is the islands?

**Comment by tylermorganwall** [comment]
When I run your code I get the correct output (no stripes): be sure to update your local version of rayshader.

```r
install.packages("remotes")
remotes::install_github("tylermorganwall/rayshader")
```
