### ISSUE TITLE
XQuartz and Rayshader Issue

### ISSUE THREAD

**Issue by redfoxgis** [tylermorganwall/rayshader#146]
Amazing software and a true pleasure to use--thank you!

There was an XQuartz update on my Mac a few weeks ago. Ever since that update, I have been unable to use Rayshader. I am not sure if this is an incompatibility issue, an XQuartz issue, or a combination of bad installs of R, and XQuartz. I have tried uninstalling and reinstalling both n times, including using different versions of R and XQuartz. I have tried doing a complete wipe of R (then reinstall) using: 

    rm -rf /Library/Frameworks/R.framework /Applications/R.app /usr/bin/R /usr/bin/Rscript

R always hangs up indefinitely after calling the rayshader library: `library(rayshader)`

Here are the R and XQuartz specs that are currently on my Mac:

MacOS Big Sur Version 11.2
XQuartz 2.7.11 (xorg-server 1.18.4)
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Platform: x86_64-apple-darwin17.0 (64-bit)

Any recommendations on how to solve this issue?

**Comment by tylermorganwall** [comment]
Does rgl work? When you run this code, does R hang?

```r
M <- matrix(rnorm(300), 3, 100, dimnames = list(c('x', 'y', 'z'), 
                                              rep(LETTERS[1:4], 25)))
M <- t(M)
rgl::points3d(M)
```

**Comment by redfoxgis** [comment]
Yes, running that code causes R to hang on my system. Thanks for the reference, I will follow that thread.

**Comment by wilrogers** [comment]
@redfoxgis and @tylermorganwall - based on the linked issue above, the best resolve seems to be running 
`options(rgl.useNULL = TRUE)
library(rgl)
library(rayshader)`

I was able to then run all of the plots from the demo for Rayshader, but you can only (as far as I have seen) render plots using 
`render_snapshot()`

**Comment by tylermorganwall** [comment]
So `render_snapshot()` does now work when `rgl.useNULL = TRUE`? Interesting, that's new—that used to produce just a black image.

**Comment by wilrogers** [comment]
@tylermorganwall sorry, you're right. I have to additionally run `rglwidget()` to get the map/plot to render in the R viewer pane. Maybe running render_snapshot is redundant? This renders a 3d, moveable object if I have a 3d plot, but it also returns a nice high res plot for 2d plots. Sorry for the confusion.

**Comment by psychemedia** [comment]
I've been rendering widgets. movies and videos fine since starting to use `rayshader` two or three weeks ago, but I seem to have updated something that has now broken `render_snapshot()` and `render_movie()` with the error:

```
Error in webshot2::webshot(f1, file = filename, selector = "#webshot", : unused argument (top = FALSE)
```

**Comment by tylermorganwall** [comment]
Yes, this was just changed in the latest version of rgl (to use the webshot2 functionality to enable snapshots when rgl.useNULL = TRUE). Probably just an oversight, although I could detect when rgl.useNULL is TRUE and then not pass the `top` argument myself.

**Comment by egayer** [comment]
Python user here, totally amazed by this beautiful package. 
I am experiencing the same problem after upgrading XQuartz. I am a sporadic user of R and sorry if my question is naive, but following @wilrogers procedure, by adding rglwidget() after one of the demos code I managed to get a figure that open in a web browser, but no R pane appears.
Would you please help me understand how to use rglwidget() so I can get a nice figure in the R pane ? (in the web browser the figure is not clean, a black line appears from the top of the DEM on one corner and the bottom of it on the other corner)
thanks,

PS: before upgrading XQuartz, everything worked fine : one figure in a R pane, another one in a XQuartz window. Now after upgrading, render_snapshot() gives a black window in the R pane (as mentioned by @tylermorganwall )

**Comment by psychemedia** [comment]
@egayer See some of the off-topic comments in https://github.com/dmurdoch/rgl/issues/8 . Issues may boil down to fiddliness related to `rgl` install, for which there is another open issue: https://github.com/dmurdoch/rgl/issues/26

**Comment by quinnpertuit1** [comment]
On a Mac, have switched to using rgl::rglwidget to view and save post-rendering.

```
library(tidyverse)
library(rayshader)
library(rgl)
options(rgl.useNULL=TRUE)

df <- tibble(x = sample(letters,20), y = sample(letters,20), z = runif(20, 1, 10)) %>% mutate_at(vars(x,y),as.factor)

p <- ggplot(df, aes(x=x, y=y, fill=z))+
  geom_tile(na.rm=FALSE)+
  scale_fill_continuous(type = "viridis", na.value='#cfcfcf')+
  theme(legend.position = 'top', panel.background = element_rect(fill='#f0f0fc'))

rgl::clear3d()

plot_gg(p)

rgl::rglwidget()
```

![image](https://user-images.githubusercontent.com/25730257/114256327-3344ad80-997e-11eb-951d-276f60a2bec9.png)

**Comment by tylermorganwall** [comment]
The issues with XQuartz should be fixed in the latest versions of rgl—anyway, it's not a rayshader bug, so I'm going to close this issue.
