### ISSUE TITLE
Warning message for sphere_shade()

### ISSUE THREAD

**Issue by hansthompson** [tylermorganwall/rayshader#15]
I ran into an issue where when I exported my heightmap for local terrain as an stl file a got a surface instead of a volume.  I traced this back to having NA's in my heightmap matrix.  Since users will want to treat NA's differently, I figured the best course of action would be just to warn them of the implications.  Sorry if this is not what you were thinking to resolve this issue. Just trying to see if I can help.

**Comment by tylermorganwall** [comment]
Thanks! I actually have a local branch working on this issue. NA's are eventually going to be used to represent "holes" in the underlying map, so plot_3d() can represent non-rectangular regions.
