### ISSUE TITLE
[New feature request] Render to gif

### ISSUE THREAD

**Issue by dieghernan** [tylermorganwall/rayshader#150]
Hi,

I am able to create gifs from an mp4 movie created with `render_movie`  via `magick/gifski` (https://docs.ropensci.org/magick/reference/video.html):
 
  ```r
file_movie <- "~/test1.mp4"
file_gif1 <- "~/test1.gif"

fps <- 30

montereybay %>%
  sphere_shade(texture="imhof1") %>%
  plot_3d(montereybay, zscale=50, water = TRUE, watercolor="imhof1",
          waterlinecolor="white", waterlinealpha=0.5)
render_movie(filename = file_movie, frames = 60, fps = fps)
rgl::rgl.close()

frames <- magick::image_read_video(file_movie, fps = fps)
magick::image_write_gif(frames, path = file_gif1, delay = 1/fps)

```

**mp4**
![mp4](https://user-images.githubusercontent.com/25656809/108076064-541e1000-706b-11eb-857a-7c6a66d3f5c2.mp4)

**gif**
![test1](https://user-images.githubusercontent.com/25656809/108076071-55e7d380-706b-11eb-98eb-615ad578603c.gif)

## The request

I would like to suggest to include all this in a new function `render_gif`. Having a look it would be very similar to `render_movie` but replacing the `av` call by a `gifski` call. The advantage would be a slower conversion time (png to gif instead of png>mp4>png>gif) but with one drawback: `gisfski` would need to be added on Suggests (as `av` or `magick`):

```r
file_gif2 <- "~/test2.gif"
fps <- 30

montereybay %>%
  sphere_shade(texture="imhof1") %>%
  plot_3d(montereybay, zscale=50, water = TRUE, watercolor="imhof1",
          waterlinecolor="white", waterlinealpha=0.5)
render_gif(filename = file_gif2, frames = 60, fps = fps)
```
![test2](https://user-images.githubusercontent.com/25656809/108076067-554f3d00-706b-11eb-9a8d-e17055222190.gif)

## Potential PR

I have prepared a code [here](https://github.com/dieghernan/rayshader/blob/master/R/render_gif.R) changing the parameter `audio` (does not make sense on gifs) by `loop`, that makes the gif to loop or not.

I would be able to send a PR if you think this can be of any interest.

Regards

**Comment by dieghernan** [comment]
I finally launched the PR, this seems to be a requested feature. Although there are other ways to create the gif without a custom function (mp4/gif conversion or render_camera/gif) I think this may be of interest for some users

**Comment by tylermorganwall** [comment]
Added directly in `render_movie()` in commit ba3a3b960f785cd4d635ad120b314863c124bf5c
