### ISSUE TITLE
render_snapshot() will NOT work... have tried a million things to fix it. PLEASE HELP!

### ISSUE THREAD

**Issue by cez2020** [tylermorganwall/rayshader#152]
Hello everyone!

I've been drawn by 3D imagery since I was a child. I have great ideas for 3D projects using rayshader. I just simply can't get render_snapshot() to work. After hours of tweaking, I am now getting the following message (in red letters) in my console:

Loading required namespace: rmarkdown

... and no plot is being generated.

PLEASE HELP!

**Comment by tylermorganwall** [comment]
Try updating to the latest version of rayshader. `rgl` changed their `snapshot3d()` function which may not work correctly on your machine. This update returns the behavior to the previous version, unless otherwise specified.
