### ISSUE TITLE
render_depth and render_movie didn't work normally for me.

### ISSUE THREAD

**Issue by aimer-entropy** [tylermorganwall/rayshader#154]
Hello, 
I tried the tutorial on my local computer, everything goes well.  But I don't know why render_movie and render_depth didn't work.
No warning or error was reported, but I just can't see the change after render_depth; and no .mp4 was found after render_movie.
Hope there's some advice.
Thanks in advance.

**Comment by tylermorganwall** [comment]
You are going to have to provide more information for me to help: please provide a minimally reproducible example of the problem on your system. Make sure to update all your packages to the latest version and then see if there's still an issue.

**Comment by tylermorganwall** [comment]
If you are still having problems you can post in this thread, but without any updates/further information I am going to close this issue.
