### ISSUE TITLE
Fix: add water to irregularly shaped map

### ISSUE THREAD

**Issue by meuleman** [tylermorganwall/rayshader#155]
https://github.com/tylermorganwall/rayshader/blob/ac4668c6291cd8c4760317ab916ae71a8869c499/R/make_water.R#L16

This results in an error in case the map to be plotted has an irregular shape (e.g. setting areas one does not want to display to `NA`).
Instead, I suggest changing this line to:
`if(all(heightmap >= waterheight, na.rm=TRUE)) {`

This was previously mentioned here, with no resolution:
https://github.com/tylermorganwall/rayshader/issues/17

**Comment by tylermorganwall** [comment]
Thanks for the bug report! Closed in c05791afa7a02908b184f84050b28c0e0c93434d.
