### ISSUE TITLE
feature question/suggestion for 3D line/path/point plots

### ISSUE THREAD

**Issue by ptoche** [tylermorganwall/rayshader#156]
Is there a way to use ``rayshader`` to produce 3D ``geom_line()`` plots and similar? Maybe in combination with package ``ggrgl``.

Package ``ggrgl`` [https://github.com/coolbutuseless/ggrgl](https://github.com/coolbutuseless/ggrgl) and its dependencies can be used to produce 2D renderings of 3D ggplots, so we can map to ``aes(x,y,z)``, which is nice, but it does not give the 3D perspective of ``rayshader`` (nor does it allow rotating the plot with a mouse). 

Also I would like to be able to export high-quality plots, as with rayshader's ``render_highquality()`` and ``render_depth()``.

Below some code that produces something in, ahem, 2.5D, perhaps a starting point.

    library(deSolve)
    library(ggplot2)
    library(ggthemes)
    library(rgl)  #remotes::install_github("dmurdoch/rgl")
    library(rayshader)  # remotes::install_github("tylermorganwall/rayshader")
    library(ggrgl)  # remotes::install_github("coolbutuseless/ggrgl", ref="main")
    library(devout)
    library(devoutrgl) ## remotes::install_github("coolbutuseless/devoutrgl", ref="main")
    library(webshot2)

    # Parameters
    parms <- c(a = 10, b = 8/3, c = 26.48)

    # Initial state 
    yini <- c(x = 0.01, y = 0.0, z = 0.0)

    # Lorenz system
    lorenz <- function(Time, State, Param) {
      with(as.list(c(State, Param)), {
        xdot <- a*(y-x)
        ydot <- x*(c-z)-y
        zdot <- x*y-b*z
        return(list(c(xdot, ydot, zdot)))
      })
    }

    # Set time horizon
    times <- seq(0, 50, by=1/200)

    # Make dataframe
    df <- as.data.frame(ode(func=lorenz, y=yini, parms=parms, times=times))

    # Make plot
    ggplot(df, aes(x=x, y=y, z=z, color=z)) +
      geom_path_3d() +
      ggtitle("Lorenz butterfly") +
      theme_minimal() -> p

    # Render Plot in window with ggrgl
    rgldev(fov=30, view_angle=-10, zoom=0.7)
    p + theme_ggrgl(16) 

    # Map color density to third variable with rayshader
    plot_gg(p, width = 5, height = 5, multicore = TRUE, scale = 250, 
            zoom = 0.7, theta = 10, phi = 30)
    Sys.sleep(1)
    render_snapshot()

    # Save plot as PDF?
    rgl::rgl.postscript(filename="~/R/lorenz3d.pdf",
                        drawText=TRUE)
    rgl::rgl.close()

<img width="710" alt="screenshot" src="https://user-images.githubusercontent.com/6339274/113784007-7df9c780-96e9-11eb-8d1b-2e3a4464a5c4.png">

**Comment by tylermorganwall** [comment]
I do believe `ggrgl` actually does allow you to make these types of plots and interact with them in 3D: while you might not be able to use `render_highquality()`, you can in fact use the `render_depth()` function with other rgl packages.

This type of "floating point/line" generic 3D plotting feature isn't really on the roadmap for rayshader (it would be a massive undertaking) so I'm going to close this issue.

**Comment by ptoche** [comment]
Thanks Tyler!
