### ISSUE TITLE
render_depth not working correct with render_label

### ISSUE THREAD

**Issue by wiesehahn** [tylermorganwall/rayshader#159]
When I try to render a scene with a depth of field effect it seems the effect is not working correctly with labels. 
(e.g. labels are not in focus although in my understanding they should be)

In the example below according to preview_focus the middle label should be totally in focus but is blurry nevertheless. Also upper and lower label should be not too far from focus plane and in my understanding should be at least less blurry. If you have a look on the right site of the rendered scene you can see that areas with the shape of the labels are in focus where there is mountain but no label.

```
montereybay %>%
  sphere_shade() %>%
  plot_3d(montereybay,zscale=50, water=TRUE, waterlinecolor="white",
          zoom=0.3,theta=-135,fov=70, phi=20) 

# add labels at different heights (distances) 
santa_cruz = c(36.962957, -122.021033)

# behind focus
render_label(montereybay,lat = santa_cruz[1], long = santa_cruz[2],
             extent = attr(montereybay, "extent"),
             altitude=2000, zscale=50, text = "Santa Cruz")

# at focus
render_label(montereybay,lat = santa_cruz[1], long = santa_cruz[2],
             extent = attr(montereybay, "extent"),
             altitude=3500, zscale=50, text = "Santa Cruz")

# closer than focus
render_label(montereybay,lat = santa_cruz[1], long = santa_cruz[2],
             extent = attr(montereybay, "extent"),
             altitude=5000, zscale=50, text = "Santa Cruz")


#Preview where the focal plane lies
render_depth(focus=0.6, preview_focus=TRUE)

#Render the depth of field effect
render_depth(focus=0.6, focallength = 100)

rgl::rgl.close()
```

Not sure if I am doing something wrong or if its a bug.

**Comment by tylermorganwall** [comment]
Thanks! Yes, this was a bug. I've updated the `render_depth()` interface and it should be working in the latest version, but you will need to update your `focus` values since the function now takes the actual distance to the focal plane.
