### ISSUE TITLE
Allow NA for plot_3d

### ISSUE THREAD

**Issue by statnmap** [tylermorganwall/rayshader#16]
First, thank you for this really nice package.  
I am playing with datasets along the coasts, which means there are some `NA` values for the area covered by the sea.  
While using `plot_3d`, the following error message arises:
```
Error in if (any(hillshade > 1 || hillshade < 0)) { : 
  missing value where TRUE / FALSE is required
```
If I find some time, I'll go through you code to test if this is possible to allow missing values. For the moment, I thought I could at least open an issue with a reprex to not forget about it !

```
library(rayshader)
library(magrittr)

data("montereybay")

montereybay[1:100, 1:100] <- NA

#We use another one of rayshader's built-in textures:
montereybay_shadow <- montereybay %>%
  sphere_shade(texture = "desert") %>%
  add_water(detect_water(montereybay), color="desert") %>%
  add_shadow(ray_shade(montereybay)) %>%
  add_shadow(ambient_shade(montereybay))

montereybay_shadow %>% 
  plot_map()

montereybay_shadow %>%  
  plot_3d(montereybay)
```

**Comment by tylermorganwall** [comment]
I actually have plans to implement support for NA values with plot_3d--see this issue:

https://github.com/tylermorganwall/rayshader/issues/15
