### ISSUE TITLE
[New Feature Request] Can we allow the use of a separate height variable (not the default colour value) when rendering ggplot2?

### ISSUE THREAD

**Issue by Kuan-Liu** [tylermorganwall/rayshader#162]
Can we allow the use of a separate height variable (not the default colour value) when rendering ggplot2? 

I am hoping to create a rayshader plot that uses a separate continuous variable to specify the height of the 3D graph. Thank you so much. I am huge fan of your work!

**Comment by tylermorganwall** [comment]
You can do this by passing in a list of two ggplots, see the bottom of this gist:

https://gist.github.com/tylermorganwall/9dc6bc30a26a4e0465f16cdf2c3fbb88
