### ISSUE TITLE
Absolute scale in plot_gg

### ISSUE THREAD

**Issue by davidfrantz** [tylermorganwall/rayshader#165]
This package is awesome for creating 3D plots! Thanks so much for this!

When generating plots for a presentation, I have encountered the following difficulty, and do wonder if there is an easy way to solve:

I am trying to do 3D maps of different cities, e.g. New York, Chicago, etc., which all look really nice by themselves.
However, I am now facing the issue of how to make the individual maps comparable in scale, as e.g. buildings are much taller in New York than in San Diego. Cities with short buildings only should also be flat in my 3D maps.

I only found the ``scale`` parameter in ``plot_gg``, but as far as I understand, this sets the scale as a function of the maximum value within each city (in relation to horizontal width). Is there an easy way to set an absolute scale?

Cheers,
David

Please see these examples that may illustrate better what I tried to describe:

![0001_New-York_New-York](https://user-images.githubusercontent.com/32633788/120600753-6c167580-c449-11eb-9167-32b56766c4ea.png)
![0010_San-Jose_California](https://user-images.githubusercontent.com/32633788/120600811-7cc6eb80-c449-11eb-9c67-7fbfe24c5f26.png)

**Comment by tylermorganwall** [comment]
The key is to set the same numeric limits for both plots in `scale_fill_continuous()`/`scale_color_continuous()`. If you keep the same `scale` in `plot_gg()`, this will ensure the two plots would be directly comparable. I'd also set `soliddepth` manually in `plot_gg()`, because otherwise it's scaled to the maximum height of the plot.

**Comment by tylermorganwall** [comment]
Feel free to comment in this issue if you have any more questions.
