### ISSUE TITLE
LiDAR 3D overlay on a basemap

### ISSUE THREAD

**Issue by Saadi4469** [tylermorganwall/rayshader#169]
Hello,

First of all thank you for creating this great package. I would like to bring your attention to a question that I just posted on [gis.tsackexchange](https://gis.stackexchange.com/questions/401941/lidar-3d-modeling-using-package-rayshader-and-las-file-in-r) . Since, you don't have a tag there, so I had to open an issue here. Your guidance and help on this would be highly appreciated.

Cheers,

**Comment by Jean-Romain** [comment]
See https://github.com/tylermorganwall/rayshader/issues/103

**Comment by tylermorganwall** [comment]
I recommend looking over the docs at www.rayshader.com for examples on how to create a map and see the `render_points()` function (see the issue @Jean-Romain posted for additional information). Additionally, you shouldn't be piping the output of `plot(...)` to anything—just pass the array generated with the rayshader functions to plot_3d() along with the height matrix.

**Comment by Saadi4469** [comment]
Thank you both!

**Comment by Saadi4469** [comment]
Hello again, 

I am having some trouble rendering the Z values in 3D. Initially, when I followed steps suggested by Jean-Romain, it worked fine as seen [here](![image](https://user-images.githubusercontent.com/55733842/122808880-45966e00-d282-11eb-98b2-bad3ff254f8a.png)), but now when I run the code again for the same file, the Z values are no longer [rendered](https://app.box.com/s/z9pumoyb6qhxwfirs40nsqoaztknv9e7), as they appear flat, even after restarting R and the computer. How can this be fixed?

```
#DTM
LAS_DTM = grid_terrain(LAS_denoised, algorithm = knnidw(k = 8, p = 2), res = 0.1)

#DTM2Matrix
LAS_DTM_mat = raster_to_matrix(LAS_DTM )

# Extent 
LAS_Extent = extent(LAS_DTM )

# Basemap
LAS_Basemap = LAS_DTM_mat %>% 
  height_shade() %>% 
  add_shadow(lamb_shade(LAS_DTM_mat ,zscale = 6),0) %>%
  add_overlay(sphere_shade(LAS_DTM_mat , texture = "desert", 
                           zscale=4, colorintensity = 5), alphalayer=0.5) %>% 
  add_shadow(ambient_shade(LAS_DTM_mat ), 0) %>%
  add_shadow(texture_shade(LAS_DTM_mat ,detail=8/10,contrast=9,brightness = 11), 0.1) 

# Rendering
LAS_Basemap %>% 
   plot_3d(LAS_DTM_mat , zscale = 1, fov = 0, theta = 13.5, zoom = 0.75, phi = 45, windowsize = c(1200, 800))
render_points(extent = LAS_Extent, long = LAS_denoised@data$X, lat = LAS_denoised@data$Y, altitude = LAS_denoised@data$Z, size = 2, color = col)
```
