### ISSUE TITLE
Non-conformable arrays error

### ISSUE THREAD

**Issue by cverdel** [tylermorganwall/rayshader#176]
[This example](https://github.com/cverdel/rayshader_experiment) used to work, but after some updates I get the following error in add_shadow():

Error in hillshade[, , 1] * scales::rescale(shadowmap, c(max_darken, 1)) : 
  non-conformable arrays

**Comment by tylermorganwall** [comment]
Thanks for the example! This was indeed a bug that should be fixed in the latest commit (5282d4396d91a2951e44f142886d5bbdb9b3c38c).

**Comment by markbneal** [comment]
Getting v26.1 resolved the conformable arrays problem, but running the demo looks like something is rotated incorrectly in monterey bay - or is it just me?
https://rpubs.com/markbneal/804286

**Comment by gadampier** [comment]
I tried all the solutions to this error https://github.com/tylermorganwall/rayshader/issues/195. None worked. Giving up and moving on.
