### ISSUE TITLE
`render_polygons()` examples are broken

### ISSUE THREAD

**Issue by matthew-law** [tylermorganwall/rayshader#180]
The examples of `render_polygons()` included in the [docs](https://www.rayshader.com/reference/render_polygons.html) don't currently actually show any polygons being rendered, instead throwing a couple of errors:

```r
#> Error in loadNamespace(x): there is no package called ‘sf’
```

which stops the data being read in, causing

```r
#> Error in nrow(polygon): object 'mont_county_buff' not found
```
downstream.

This should be easy to fix by specifying `sf` somewhere – I think [this](https://github.com/tylermorganwall/rayshader/blob/master/R/render_polygons.R) is the relevant file but I'm not sure how to explicitly specify the package. At the moment it's done so with `sf::st_simplify()` and `sf::st_buffer()`, but it looks like this isn't good enough for whatever it is that renders the documentation (I think `pkgdown`?).

**Comment by matthew-law** [comment]
I've just found another similar issue for `generate_polygon_overlay()` [here](https://www.rayshader.com/reference/generate_polygon_overlay.html):

```
#> Error in generate_polygon_overlay(monterey_counties_sf, palette = rainbow,     extent = attr(montereybay, "extent"), heightmap = montereybay): {sf} package required for generate_line_overlay()
```

so I suspect this might also be an issue in other places throughout the website.

**Comment by glorious1** [comment]
Have you installed the package 'sf'?  If not, that's what you need to do.

**Comment by matthew-law** [comment]
> Have you installed the package 'sf'? If not, that's what you need to do.

@glorious1 the issue isn't with any code I'm running locally, it's with the examples shown on the rayshader website on the pages I liked to ([this one](https://www.rayshader.com/reference/render_polygons.html) and [this one](https://www.rayshader.com/reference/generate_polygon_overlay.html)) which currently don't show what they're supposed to because of the errors mentioned:

![image](https://user-images.githubusercontent.com/18603830/132043563-53add055-e030-4123-b2e0-58fae81486fb.png)

**Comment by tylermorganwall** [comment]
Thanks for the report, the examples are fixed.
