### ISSUE TITLE
problem adding shades

### ISSUE THREAD

**Issue by luizesser** [tylermorganwall/rayshader#181]
Dear all,
(before anything, I am using the CRAN version in a ARM MacAir)
I was struggling to follow the tutorial in read me, once every time I called add_shadow function a error returned as follow:
Error in hillshade[, , 1] * scales::rescale(shadowmap, c(max_darken, 1)) :                       
  non-conformable arrays
In the source code I realized that scales::rescale is multiplied by one dimension of hillshade, thus I transformed the hillshade[,,n] into a vector. This solved the issue. 

hillshade[,,1] = as.vector(hillshade[,,1]) * scales::rescale(shadowmap,c(max_darken,1))

But then another issue arised with transposition using flipped function.
I have changed it to:

t(apply(shadowmap, 2, rev))

And the problem was solved.
It seems that everything is fine. But I would like to know if you can find any hidden issue with my solution that I have passed by.

Thanks for everything.
Bests,
Luíz

**Comment by tylermorganwall** [comment]
This was brought up and fixed in this issue, https://github.com/tylermorganwall/rayshader/issues/176.

Update to the latest version on github, or install from r-universe if you can't build from source:

```
options(repos = c(
    tylermorganwall = 'https://tylermorganwall.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

# Install some packages
install.packages('rayshader')
```
