### ISSUE TITLE
generate_label_overlay: many labels for one feature

### ISSUE THREAD

**Issue by glorious1** [tylermorganwall/rayshader#183]
I have an sf object with a single feature, a linestring representing a stream:
```
> mk_streams
Simple feature collection with 1 feature and 4 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: -155.385 ymin: 19.88843 xmax: -155.3645 ymax: 19.92818
Geodetic CRS:  NAD83 (with axis order normalized for visualization)
             osm_id                 name intermittent waterway                       geometry
253751526 253751526 Kapoholimuele Stream          yes   stream LINESTRING (-155.3846 19.88...
```
When I make a label with generate_label_overlay and add it to the map, I get a great many labels all over each other up and down the stream.  I guess it's generating a label for each pair of coordinates.  The same thing happens with roads.

Is there a way to get just the one per feature, short of adding it manually?

**Comment by tylermorganwall** [comment]
Via the documentation, the `generate_label_overlay()` either takes a character vector of labels, or an `sf` object with `POINT` geometry and a column for labels. You'll need to extract POINT geometry from the stream LINESTRING object to tell the function exactly where the label should go (e.g. the midpoint of the line or some other suitable place).
