### ISSUE TITLE
Error when installing 'rayshader' on AWS

### ISSUE THREAD

**Issue by joaneeet7** [tylermorganwall/rayshader#186]
Hi, I have been trying to solve this problem for a few hours but I can't find any way to do it. The command that I have used is: `install.packages("rayshader")`

I have tried to install the 'rayshader' package on an AWS machine with an EC2 instance. The intention of this installation is to be able to run a make command for the auto creation of a RMD report containing 3D graphics from 'rayshader'.

The errors returned by the execution are as follows:
```
/usr/share/R/share/make/shlib.mk:6: recipe for target 'RcppArmadillo.so' failed
make: *** [RcppArmadillo.so] Error 1
ERROR: compilation failed for package ‘RcppArmadillo’
* removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo’
ERROR: dependencies ‘jpeg’, ‘RcppArmadillo’ are not available for package ‘rayimage’
* removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.4/rayimage’
ERROR: dependencies ‘raster’, ‘rayimage’, ‘RcppArmadillo’ are not available for package ‘rayshader’
* removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.4/rayshader’

The downloaded source packages are in
	‘/tmp/RtmpDWE73c/downloaded_packages’
Warning messages:
1: In install.packages("rayshader") :
  installation of package ‘jpeg’ had non-zero exit status
2: In install.packages("rayshader") :
  installation of package ‘RcppArmadillo’ had non-zero exit status
3: In install.packages("rayshader") :
  installation of package ‘rayimage’ had non-zero exit status
4: In install.packages("rayshader") :
  installation of package ‘rayshader’ had non-zero exit status

```

Please, any help would be greatly appreciated, best regards!

**Comment by tylermorganwall** [comment]
You just need to install the listed packages--search google for `install R ::name of package:: ubuntu` for each of the packages listed for assistance. Install the packages from source if binaries are not available.
