### ISSUE TITLE
No visible global function definition for 'png'

### ISSUE THREAD

**Issue by markbneal** [tylermorganwall/rayshader#188]
Just an FYI - I built the rayshader 0.26.1 on r-hub (my windows machine was having problems building stuff), and it provided some feedback on `png`. Full details:

rayshader 0.26.1: NOTE
Build ID:	rayshader_0.26.1.tar.gz-47a32fe5a62deda057401f70ce4ef468
Platform:	Windows Server 2008 R2 SP1, R-release, 32/64 bit
Submitted:	10 minutes 17.2 seconds ago
Build time:	8 minutes 36.6 seconds
NOTES:
* checking installed package size ... NOTE
  installed size is  6.0Mb
  sub-directories of 1Mb or more:
    data   2.9Mb
    libs   2.5Mb
* checking R code for possible problems ... NOTE
**plot_gg: no visible global function definition for 'png'
  png
Consider adding
  importFrom("grDevices", "png")
to your NAMESPACE file.**
Undefined global functions or variables:
See the full build log: HTML, text, artifacts.
Have questions, suggestions or want to report a bug? Please file an issue ticket at GitHub. Thank You for using the R-hub builder.

**Comment by tylermorganwall** [comment]
Thanks! This should be fixed in the latest version.
