### ISSUE TITLE
render_highquality() results in unexpected output

### ISSUE THREAD

**Issue by wiesehahn** [tylermorganwall/rayshader#196]
When rendering a scene from nadir / topview (azimuth = 90) `render_highquality()` results in a strange output image. 
`render_snapshot()` on the other hand is working as expected. 
With e.g. azimuth =88 result is as expected also for `render_highquality()`.
```
testmat <- resize_matrix(montereybay, scale = 0.5)

testmat %>%
  sphere_shade() %>%
  plot_3d(montereybay,zscale=50,zoom=0.6,theta=-90,phi=90)

render_snapshot("good.png") 
render_highquality("bad.png")
```

**Comment by tylermorganwall** [comment]
Thanks! This should be fixed in the latest version (b74dd271e12b047bc9f790f4fae248c52171e26f).
