### ISSUE TITLE
Raster to Matrix Transformation Error

### ISSUE THREAD

**Issue by christophermallon** [tylermorganwall/rayshader#2]
Hi Tyler,

First of all, you have done really fantastic work. I'm an analyst with the Government of Alberta (it's one of the provinces of western Canada) and I do a lot of cartography and geomatics. I am very excited to use your work to produce some beautiful maps! After testing your code, it looks like there is a minor issue with creating the input matrix: the y-axis coordinates seem to be reversed. You can see it in the test data you have already used: if you compare [your test data](https://github.com/tylermorganwall/rayshader/blob/master/README.md) with [a google map of the outlet of the Derwent River](https://www.google.ca/maps/@-42.7660482,147.1787996,17174m/data=!3m1!1e3), you'll see what I mean. 

I'm pretty new at R-based spatial analysis, but it seems this can be corrected before you use the sphere_shade() function by pre-rotating the matrix:

`tif_file = raster::raster("dem_01.tif")`
`elmat = as.matrix(tif_file)`
`elmat = t(elmat)[,nrow(elmat):1]`
`elmat %>%`
`  sphere_shade(texture = "desert") %>%`
`  plot_map()`

And produces this output, correctly orientated:
![derwent_rotated](https://user-images.githubusercontent.com/15743083/42400250-17716a6e-812e-11e8-8376-204016098bb3.png)

I'm sure you can find a more elegant solution, but for now, I hope this helps you improve your already fantastic work. It's great to find others with a passion for mapping and data visualization.

Warm regards,
Chris

**Comment by tylermorganwall** [comment]
Glad you're enjoying it!

The orientation is to align `plot_map` with the base R `image` and `contour` functions. Base R has a bit of a strange convention when plotting matrices/contour plots, which is reflected here.

From the `image` documentation:
>Notice that image interprets the z matrix as a table of f(x[i], y[j]) values, so that the x axis corresponds to row number and the y axis to column number, with column 1 at the bottom, i.e. a 90 degree counter-clockwise rotation of the conventional printed layout of a matrix.

You can see this by comparing the output of `image(volcano)` with `plot_map(sphere_shade(volcano))` and this call to `raster::plotRGB`:
```r
raster::plotRGB(raster::brick(array(volcano/max(volcano),
                              dim=c(nrow(volcano),ncol(volcano),3))),scale=1)
```

I'll include `flipv` and `fliph` options in the next version so the user can easily change the orientation if they want to. I also may change the default in the future, but there are some aspects of development right now that are easier if it matches base R.

**Comment by christophermallon** [comment]
Interesting stuff, looks like I have a lot to learn about mapping in R. Thanks again for the work, and for your explanation. Looking forward to working with rayshader in the future!

**Comment by tylermorganwall** [comment]
FYI, this has been changed in the latest verion--enjoy!

**Comment by mo-sco** [comment]
Hi Tyler, 

Rayshader is an amazing package, thanks so much! I am working on the Great Barrier Reef mapping fish movements with underwater bathymetry, but being new to the program I am still unsure how your functions work so apologies if this is a silly question. I would like to create my own texture (create_texture) for my bathymetry because the default options too dark, but when I try and create my own texture using your code here: [https://github.com/tylermorganwall/rayshader/blob/master/R/create_texture.R]
I get the error: "Error in bilineargrid(colorarray[, , i]/256) : 
  could not find function "bilineargrid"
Here is my code and under #plot bathymetry is where I have tried to use the function
Thanks very much for your help!
## Plotting 3D KUD and bathymetry
bath <- crop(bath_ras_utm, extent(stat) + 500) *-1

## Set depth exaggeration
depth_exaggeration = 1.5

create_texture("lightblue", "lightblue3","tan","lemonchiffon2","khaki4") %>%
  plot_map(bath)

## plot bathymetry
bath %>%
  as.matrix() %>%
  create_texture("lightblue", "lightblue3","tan","lemonchiffon2","khaki4") %>%
  add_shadow(ray_shade(as.matrix(bath), 
                       zscale = 1/depth_exaggeration), 0.1) %>%
  add_shadow(ambient_shade(as.matrix(bath), 
                           zscle = 1/depth_exaggeration), 0.1) %>%
  plot_3d(
    as.matrix(bath),
    solid=TRUE,
    soliddepth="auto",
    solidcolor = 'white',
    solidlinecolor = "grey50",
    shadow = TRUE,
    water = TRUE,
    background='white',
    zscale = 1/depth_exaggeration,
    waterdepth = 0,
    watercolor = "#88DDFF",
    wateralpha = 0.3,
    waterlinecolor = "white",
    waterlinealpha = 0.5,
    windowsize = c(1200, 700),  ## Size of window
    theta = -135,               ## Play around with the theta, phi, fov and zoom to orient the plot (or you can adjust it manually)
    phi = 20,
    fov = 60,
    zoom = 0.8
  )

**Comment by tylermorganwall** [comment]
Create texture is passed to the `texture` argument in `sphere_shade()`, replace your call to `create_texture` with 
 
```r
bath %>%
  as.matrix() %>%
  sphere_shade(texture=create_texture("lightblue", "lightblue3","tan","lemonchiffon2","khaki4"), zscale = 1/depth_exaggeration) %>%
  add_shadow(ray_shade(as.matrix(bath), zscale = 1/depth_exaggeration), 0.1) %>%
  add_shadow(ambient_shade(as.matrix(bath), zscale = 1/depth_exaggeration), 0.1) %>%
  plot_3d(as.matrix(bath),solid=TRUE,soliddepth="auto",solidcolor = 'white',solidlinecolor = "grey50",shadow = TRUE,water = TRUE,background='white',zscale = 1/depth_exaggeration,waterdepth = 0,watercolor = "#88DDFF",wateralpha = 0.3,waterlinecolor = "white",waterlinealpha = 0.5,windowsize = c(1200, 700), theta = -135,phi = 20, fov = 60, zoom = 0.8)
```

**Comment by mo-sco** [comment]
Thanks so much for your quick response Tyler,


I have added the new code to mine, but I am still getting this error message:

"Error in bilineargrid(colorarray[, , i]/256) :
  could not find function "bilineargrid"

Any ideas how to resolve this? I have found your bilinear function code from this page: https://github.com/tylermorganwall/rayshader/blob/master/src/bilineargrid.cpp

But I am not sure what to put in the first line of code: inline double bilinearinterp(double q11, double q12, double q21, double q22, double x, double y)

Thank you for your time, I really appreciate your help.

Cheers,
Molly



________________________________

**Comment by nahin29** [comment]
I'm getting this error. how to solve it @tylermorganwall ![Screenshot 2021-02-18 122115](https://user-images.githubusercontent.com/62886579/108314288-d9c4cb80-71e3-11eb-8857-4b0fa59acb52.png)

**Comment by nahin29** [comment]
@tylermorganwall 
my code
library(rayshader)
library(sp)
library(raster)
library(scales)

#elevation data 
elevation1 = raster::raster("D:/R/r essential/programming books/R/RS with R/sundarban N21E089.SRTMGL1/N21E089.hgt")
elevation2 = raster("D:/R/r essential/programming books/R/RS with R/sundarban N22E089.SRTMGL1/N22E089.hgt")

elevjoin = raster::merge(elevation1,elevation2)

height_shade(raster_to_matrix(elevjoin)) %>% plot_map()
