### ISSUE TITLE
error with make_base_cpp

### ISSUE THREAD

**Issue by will-r-chase** [tylermorganwall/rayshader#20]
installed the latest version from github, but it seems the make_base cpp export got lost in the latest update. Now when I try plot_3d(solid = TRUE) I get the error:

Error in make_base_cpp(heightmap1, heightmap2, heightmap3, heightmap4,  : 
  object '_rayshader_make_base_cpp' not found

**Comment by tylermorganwall** [comment]
Try removing the prior installation and re-installing it. It's likely that the old installation was not fully removed. Also remember you need to include the heightmap as the first argument in `plot_3d()`

**Comment by will-r-chase** [comment]
Yeah sorry lazy typing, I had the first argument as the elevation matrix. You were right, did a clean install and it's all good now. New update is fast fast fast btw 🔥  Now on to more add_overlay() testing!
