### ISSUE TITLE
Can't set numbercores in ray_shade on windows

### ISSUE THREAD

**Issue by Lvulis** [tylermorganwall/rayshader#203]
The way `ray_shade` with `multicore=T` picks up `numbercores` doesn't allow for changing the number of cores to be used on Windows. The `numbercores` is determined either by checking the global options for `cores` which doesn't seem to exist on Windows (unless I am sorely mistaken!) or by using `parallel::detectCores`. See code snippet below:
```
if (is.null(options("cores")[[1]])) {
      numbercores = parallel::detectCores()
    }
    else {
      numbercores = options("cores")[[1]]
    }
```

On my machine (Win10 20H2 OSBUILD: 19042.1466)
```
> options("cores")
$cores
NULL
```

This is an issue as I don't want to use all my cores at once, but only some. It seems the point of having `options("cores")` is so we can manually change the number of cores to be used, but there isn't a simple way to add an option by assignment. The easiest way to fix this, in my humble opinion, would be to simply pass `numbercores` as an argument to `ray_shade` when `multicore=T` instead of the current method.

I've forked and made this change, and could submit it as a PR.

**Comment by tylermorganwall** [comment]
You can set options("cores") yourself at the beginning of your R session, it's not set automatically with your machine. Example:

```
> options("cores")
$cores
NULL

> options("cores"=4)
> options("cores")
$cores
[1] 4
```

**Comment by Lvulis** [comment]
Nice, thanks! Learned something new about R today.
