### ISSUE TITLE
render_label() with out-of-bounds location plots label multiple time a "noisy" location

### ISSUE THREAD

**Issue by HenrikBengtsson** [tylermorganwall/rayshader#205]
Example of problem:

![issue](https://user-images.githubusercontent.com/1616850/149906514-354e3c18-f80c-4df2-a515-f8011954dbe7.png)

Produced by:

```r
library(rayshader)
montereybay %>% sphere_shade() %>% plot_3d(montereybay, zscale=50)

santa_cruz <- c(36.962957, -122.021033)
render_label(montereybay,lat=santa_cruz[1], long=santa_cruz[2],
             extent=attr(montereybay, "extent"),
             zscale=50, text="Santa Cruz")

out_of_bounds <- c(37.20, -122.021033)
render_label(montereybay,lat=out_of_bounds[1], long=out_of_bounds[2],
             extent=attr(montereybay, "extent"),
             zscale=50, text="Out of bounds")
```

This is with **rayshader** 0.26.8 (commit dc1bb008) on Ubuntu 18.04.

# Expected behavior

When `out_of_bounds` is outside the region, I'd expect one of the following things to happen:

* an error is produced
* a warning is produced, and no label is added
* a warning is produced, and the label is added with a line that goes all the way to the "bottom"
* the label is added with a line that goes all the way to the "bottom"

**Comment by tylermorganwall** [comment]
Thanks! Fixed in 89119188054b9c38c09b49ffdc28a6d632f24f3f.
