### ISSUE TITLE
wrong result with multiple floating overlays and render_highquality()

### ISSUE THREAD

**Issue by wiesehahn** [tylermorganwall/rayshader#210]
When rendering multiple floating overlays at different heights `render_highquality()` renders the first overlay multiple times.

e.g.:
```
library(rayshader)
library(sf)

polys1 <- monterey_counties_sf %>% dplyr::filter(ALAND <= 291773605)
polys2 <- monterey_counties_sf %>% dplyr::filter(ALAND > 291773605)

poly_overlay1 <- generate_polygon_overlay(polys1, palette = rainbow, 
                                          extent = attr(montereybay,"extent"), heightmap = montereybay)

poly_overlay2 <- generate_polygon_overlay(polys2, palette = rainbow, 
                                          extent = attr(montereybay,"extent"), heightmap = montereybay)

montereybay %>%
  height_shade() %>%
  add_shadow(ray_shade(montereybay,zscale=50),0.3) %>% 
  plot_3d(montereybay)

#Render Floating Overlays
render_floating_overlay(poly_overlay1, altitude = 5000,zscale = 50, alpha = 1)
render_floating_overlay(poly_overlay2, altitude = 10000,zscale = 50, alpha = 1)
```

`render_snapshot()` works as expected:
![multioverlay_snapshot](https://user-images.githubusercontent.com/41429613/152687284-741f52ab-4171-410e-ac08-5e002034b252.png)

while `render_highquality()` does this:
![multioverlay_highquality](https://user-images.githubusercontent.com/41429613/152687350-604f0eac-93c9-45f3-b456-05ffb3d79b1c.png)

**Comment by tylermorganwall** [comment]
This is working on my system—Can you provide more information on your system via `sessionInfo()`?

**Comment by wiesehahn** [comment]
see here https://github.com/tylermorganwall/rayshader/issues/208#issuecomment-1030897207

**Comment by tylermorganwall** [comment]
See this comment, try it out and tell me if it fixes your problem:

https://github.com/tylermorganwall/rayshader/issues/208#issuecomment-1032012029

**Comment by wiesehahn** [comment]
Unfortunately, updating to the latest rgl version does not solve this issue.

Actually it seems a little random. I ran the code a couple of times and in one case the upper (second) overlay was rendered duplicated.

**Comment by tylermorganwall** [comment]
What happens if you set a `cache_filename` in `render_highquality()`? 

I also recommend fully uninstalling rayshader on your system, and then doing a fresh install. Check your package directory (call `.libPaths()`) and make sure it's deleting the old version. I have found problems with Windows not actually uninstalling packages in the past.

**Comment by wiesehahn** [comment]
When setting the `cache_filename` the cached layer files were correct, but the rendered image still displayed two times the first layer. 

But your second suggestion to simply do a fully reinstall of rayshader seems to do the trick, thanks.

![multioverlay_reinstall](https://user-images.githubusercontent.com/41429613/153139947-215f7d8a-1d10-4ccd-8384-352316d9f252.png)

**Comment by tylermorganwall** [comment]
Great!
