### ISSUE TITLE
add_overlay alphacolor requires 4 layers when docs say 3

### ISSUE THREAD

**Issue by apsteinmetz** [tylermorganwall/rayshader#212]
The docs say 'alphacolor' is used to set a transparency color when using a 3 layer RGB array (no alpha channel).  This breaks, however:

```
montereybay %>% 
  sphere_shade() %>% 
  add_overlay(height_shade(montereybay),alphacolor = "white") %>% 
  plot_map()

#Error in overlay[alphalayer1, 4] <- 0 : 
#incorrect number of subscripts on matrix
```
It looks like the function is asking for a 4-layer array.  Thanks.

**Comment by tylermorganwall** [comment]
Thanks, this was a bug—fixed in 5390d6a80bf656b752bf1218e41316c164fc45ff.
