### ISSUE TITLE
save_png not write_png

### ISSUE THREAD

**Issue by keum** [tylermorganwall/rayshader#22]
Hi Tyler, 
I love your rayshader....
I noticed that updated version should have **save_png** instead of write_png in Read.me landing page. 

~~write_png~~ **_save_png_** Writes the current map to disk with a user-specified filename.

**Comment by tylermorganwall** [comment]
Thanks for pointing this out! It's fixed in the next version.

**Comment by tylermorganwall** [comment]
Fixed 29fdae30aa440d85d0cf1db42450238425f14fa3
