### ISSUE TITLE
Close_previous inop after RGL update

### ISSUE THREAD

**Issue by ryanaskren** [tylermorganwall/rayshader#220]
Hey @tylermorganwall,

Appreciate all of work and the time you put into this suite of packages. I recently update several packages (including 'rgl') and can no longer get the clear_previous = TRUE part of any of the render functions to work. 

I'm working with:
'rayshader' -> 0.27.2 and 'rgl' -> 0.108.2

Is that a widespread issue with these updates or do I have version control issues with a different package?

Again, appreciate all of your help!

Ryan

**Comment by tylermorganwall** [comment]
Update to the latest version of rgl, also see this issue:

https://github.com/tylermorganwall/rayshader/issues/208
