### ISSUE TITLE
Continuous color palettes map incorrectly in `generate_polygon_overlay`

### ISSUE THREAD

**Issue by SimonTopp** [tylermorganwall/rayshader#221]
Continuous color palettes map based on the order of the values in the sf dataframe rather than sequentially based on the value of the attribute provided in `data_column_fill`.   This is problematic if your data column is quantitative.  An easy fix might be just arranging the cropped sf polygon by the data column somewhere in the function.

Reproducible example
```
library(rayshader)
library(tidyverse)

water_palette = colorRampPalette(c("darkblue", "dodgerblue", "lightblue"))(200)
bathy_hs = height_shade(montereybay, texture = water_palette)

generate_polygon_overlay(monterey_counties_sf, palette = rainbow, 
                         extent = attr(montereybay,"extent"), data_column_fill = 'AWATER', heightmap = montereybay) %>%
  add_overlay(generate_altitude_overlay(bathy_hs, montereybay, start_transition = 0)) %>%
  plot_map()


generate_polygon_overlay(monterey_counties_sf %>% arrange(AWATER), palette = rainbow, 
                         extent = attr(montereybay,"extent"), data_column_fill = 'AWATER', heightmap = montereybay) %>%
  add_overlay(generate_altitude_overlay(bathy_hs, montereybay, start_transition = 0)) %>%
  plot_map()
```
Resulting maps
![image](https://user-images.githubusercontent.com/33098707/159358678-8ee9c102-4193-46fe-b90d-cba55868790e.png)
![image](https://user-images.githubusercontent.com/33098707/159358695-de0a8f07-2c2b-4cf8-b8fd-dc74a11221b7.png)

**Comment by tylermorganwall** [comment]
This bug was actually a little worse than that: It wasn't mapping the continuous palette at all, due to a 0-index bug resulting in basically random values being assigned. The behavior was supposed to be what you described. If you try the latest version, you should see the actual correct continuous mapping.

**Comment by tylermorganwall** [comment]
Also, thanks for the bug report!

**Comment by SimonTopp** [comment]
Thanks for developing and maintaining such a cool package!
