### ISSUE TITLE
plot_gg() with xy plots running into an error

### ISSUE THREAD

**Issue by koustubhsharma** [tylermorganwall/rayshader#227]
I have been trying to transform some simple xy plots into 3D, but keep running into an error:
Error in hillshade[, , 1] * scales::rescale(shadowmap, c(max_darken, 1)) : 
  non-conformable arrays

This happens even for the example codes on the vignette, even though I am able to make 3D plots with the volcano and diamonds options, but not with mtcars and data. I recently updated the rayshader package from github (version 0.24.10), following a similar issue someone posted on reddit. Just want to also flag that I am able to use sphere_shade, plot_3D and render_points without any problems. I am also unable to figure out how to overlay points of variable size (based on a column) on a 3D map.

Thanks much in advance,

**Comment by tylermorganwall** [comment]
Check out issue https://github.com/tylermorganwall/rayshader/issues/176 and https://github.com/tylermorganwall/rayshader/issues/181, reinstall all ray* packages, restart and reload R, and see if that fixes your problem

**Comment by koustubhsharma** [comment]
Thanks Tyler,

Uninstalling, physically removing and reinstalling all ray packages did the trick.

 

I have one follow up question: you mention interactive renderer on your tweets but I can’t seem to find any sources to create animations using multiple scenes.

 

Thanks in advance, Koustubh

**Comment by tylermorganwall** [comment]
See this youtube video for a tutorial on animations with the interactive renderer:

https://www.youtube.com/watch?v=fZ3RvNezIrw

**Comment by koustubhsharma** [comment]
Thanks!
