### ISSUE TITLE
R session abort when loading rayshader

### ISSUE THREAD

**Issue by ppramg** [tylermorganwall/rayshader#229]
Hello,

I'm sorry if this makes a duplicate, but as the other issue is closed I'm not sure if you'll see it.
Everything is in the title. I installed latest versions of Rstudio, Rtools and R, but as soon as I call the library (rayshader), R session aborts...
I tried to install from cran and from your github, and I tried to completely remove the rgl package but nothing helped...
I f you have a suggestion to fix that I would be very grateful !

Thanks for your great work by the way, I love your packages.

**Comment by MarcelHWachter** [comment]
Hi,

I have the same issue in Rstudio, but I think the issue here lies with RStudio. I do not have this problem when I load the package from the terminal or VS code.

**Comment by ppramg** [comment]
Hi,
Thank you for your response. Indeed it's the same here, it works when I load the package from R terminal outside from Rstudio. I'll try to get use to used to R without Rstudio for these purpose !
Thank you again !

**Comment by MarcelHWachter** [comment]
This might be relevant: [https://github.com/rstudio/rstudio/issues/11076](url)
There is a patch for R 4.2.0: [https://cran.r-project.org/bin/windows/base/rpatched.html](url)
But I haven't tried it yet.

**Comment by tylermorganwall** [comment]
I believe this was an issue with RStudio and is fixed in the latest versions of R/RStudio.
