### ISSUE TITLE
Base Block is too thick

### ISSUE THREAD

**Issue by Kaitohooi** [tylermorganwall/rayshader#237]
Can I know why would the base block is so thick that makes the 3d plot so small? Is there a way to solve this problem pls

![image](https://user-images.githubusercontent.com/79246620/184479662-e112f3b8-9f39-4f4f-9cb4-61e526303b6a.png)

**Comment by tylermorganwall** [comment]
Yes, manually set the `soliddepth` argument from `"auto"` to some other depth in `plot_3d()` or `plot_gg()`.

**Comment by Kaitohooi** [comment]
Hello @tylermorganwall, my code is basically from your scatterplot sample, but I don't know why the problem still persist.

![image](https://user-images.githubusercontent.com/79246620/184519612-dc19f114-236d-4a90-b522-dae732694987.png)
![image](https://user-images.githubusercontent.com/79246620/184519621-4ddde60f-f154-4e67-9ee2-5bc37fd638cd.png)

**Comment by tylermorganwall** [comment]
Set the soliddepth to something like -1 (play around with the value until you find one that works).

**Comment by Kaitohooi** [comment]
alright, it works! Thanks for your suggestion @tylermorganwall
