### ISSUE TITLE
Error in parse(outFile)  - Error when compiling

### ISSUE THREAD

**Issue by JasonCurole** [tylermorganwall/rayshader#240]
Thanks so much for what looks like an amazing package.

I am receiving the following error when compiling from source:

Error in parse(outFile) : 
  /tmp/RtmpWZby3b/R.INSTALL9781f7584afd5/rayvertex/R/add_shape.R:772:30: unexpected '>'
771:     scaleval = (bbox_size + material$toon_outline_width)/bbox_size
772:     single_obj = single_obj |>
                                  ^
ERROR: unable to collate and parse R files for package ‘rayvertex’

Downloading from:
trying URL 'https://tylermorganwall.r-universe.dev/src/contrib/rayvertex_0.4.5.tar.gz'

Please let me know if you need any other information.

**Comment by tylermorganwall** [comment]
rayvertex requires R 4.1 or greater as it uses the native pipe. Update to the latest version of R and rayvertex should install without issues.
