### ISSUE TITLE
Trouble installing rayvertex

### ISSUE THREAD

**Issue by Lunkster** [tylermorganwall/rayshader#244]
Hi. So curious trying this package out but I fail when installing
AV Linux MX-21 Edition (Debian)

I've tried both from github and CRAN. I have reinstalled R and I'm out of ideas.

Any ideas?

Cheers
/Henrik

installing to /home/henrik/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-rayvertex/00new/rayvertex/libs
** R
Error in parse(outFile) : 
  /tmp/Rtmpx1ibMt/R.INSTALL15c404a8717f5/rayvertex/R/add_shape.R:795:30: unexpected '>'
794:     scaleval = (bbox_size + material$toon_outline_width)/bbox_size
795:     single_obj = single_obj |>
                                  ^
ERROR: unable to collate and parse R files for package ‘rayvertex’
* removing ‘/home/henrik/R/x86_64-pc-linux-gnu-library/4.0/rayvertex’

The downloaded source packages are in
	‘/tmp/RtmpZ9I0kt/downloaded_packages’
Warning message:
In install.packages("rayvertex") :
  installation of package ‘rayvertex’ had non-zero exit status

**Comment by Lunkster** [comment]
Gave up and installed Ubuntu 22.04 in VirtualBox. Not a walk in the park there either.
After some installation errors I had to install these packages to a clean Ubuntu install:

make  g++ libfontconfig1-dev libharfbuzz-dev libfribidi-dev r-base-dev

But then it worked. 
AV Linux still unsolved

**Comment by tylermorganwall** [comment]
rayvertex requires R 4.1 or greater as it uses the native pipe. If that version of R is not available in AV Linux, you will have to manually build and install R for rayvertex to work.
