### ISSUE TITLE
Title and title bar behavior when rendering

### ISSUE THREAD

**Issue by HRodenhizer** [tylermorganwall/rayshader#246]
First off, thanks so much for this package. It's powerful and really awesome!

When I create a snapshot or movie with a title on two lines (manually creating the newline with '\n') and title bar, the text works as expected, but the title bar does not extend to cover both lines. Some way to manually specify the height of the bar or automatically increase the height would be awesome.

![title_overflows_box](https://user-images.githubusercontent.com/38510539/200873467-8080eac3-2fc3-4794-8b4a-85a747f9b749.png)

While creating this issue, I also realized that a long title without a manually specified newline just runs off the right side of the page. Support for automatic wrapping would be very useful.

![title_runs_off_page](https://user-images.githubusercontent.com/38510539/200874266-8fc3efe8-f889-45c9-91c2-385d602b6057.png)

**Comment by tylermorganwall** [comment]
This is actually a rayimage issue, which does the processing and rendering of titles. Update to the latest version on github and it should account for newlines in your title bar width. 

```r
remotes::install_github("tylermorganwall/rayimage")
```

**Comment by HRodenhizer** [comment]
Awesome, thanks! Any plans to support automatic wrapping?

**Comment by tylermorganwall** [comment]
If it becomes a feature in the magick package yes, but no plans to add that capability myself
