### ISSUE TITLE
Adding paths to a plot_gg surface

### ISSUE THREAD

**Issue by otills** [tylermorganwall/rayshader#253]
Really neat package!Is there anyway of rendering paths and points onto a plot produced using plot_gg()?

The examples seem orientated towards the map plotting functions, and I get errors such as these when I try to apply them to a data plot.

`Error in render_path(lat = 10, long = 10, altitude = 10) : 
  trying to get slot "xmin" from an object of a basic class ("NULL") with no slots`

**Comment by tylermorganwall** [comment]
This is not currently possible as ggplots don't have a consistent coordinate reference system that can be used to place data into the scene (e.g. there are multiple reference systems present in a faceted plot).
