### ISSUE TITLE
render_path not producing output and convert_path_to_animation_coords error message

### ISSUE THREAD

**Issue by PJV-Ecu** [tylermorganwall/rayshader#256]
Dear Dr. Morgan-Wall,

I am finding a problem I cannot solve for the function "render__path" and its follow-up function "convert_path_to_animation_coords". 

1) After running render_path on the 3D render image, there is no visible output for the requested path, but the command runs without providing an error message. I have checked for the integrity of the original GeoTIFF file, and it looks consistent, it includes a valid "Extent" attribute with proper coordinates. The resulting elevation matrix has "NA" values, I do not know if that may be the issue. I have replicated your tutorial without problems at https://www.rayshader.com/reference/convert_path_to_animation_coords.html
I have modified the extent of the path circle I expect to render, to see if the 3D image in the rgl window reacts by changing scale; however, the code runs without error messages but the render in the rgl window remains unchanged, yet it is active as I can rotate and zoom. It seems that the script runs, but it does not render the path.

2) In an attempt to generate animation coordinates, the process runs for a few seconds and the resulting error message is:

Error in if (max(linearized_cp$total_dist) < 1e-07) { : 
  missing value where TRUE/FALSE needed
 
The source GeoTIFF raster file can be downloaded from: https://www.dropbox.com/t/cWJMbHt7aGg7Nsjt

Code follows.

`
library(rayshader)
library(raster)
library(osmdata)
library(sf)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(paletteer)

#Generate a circle in the 3D rendered image and fly around on top of it

#Preliminaries
localtif = raster::raster("Elevacion_cuenca.tif")

elmat = raster_to_matrix(localtif)

base_map = elmat %>% 
    height_shade() %>%
    add_overlay(sphere_shade(elmat, texture = "desert", colorintensity = 5), alphalayer=0.5) %>%
    add_shadow(lamb_shade(elmat), 0) %>%
    add_shadow(ambient_shade(elmat),0) %>% 
    add_shadow(texture_shade(elmat,detail=8/10,contrast=9,brightness = 11), 0.1)

plot_map(base_map)

#Plot 3D and render path
base_map %>% 
    plot_3d(elmat, zscale = 50, windowsize=c(1200,800), solid = TRUE, soil = FALSE)

mount_imbabura_coord = c(-78.18, 0.26)
t = seq(0,2*pi,length.out=1000)
circle_coords_lat = mount_imbabura_coord[1] + 0.09 * sin(t)
circle_coords_long = mount_imbabura_coord[2] + 0.09  *  cos(t)

render_path(
    extent = attr(localtif,"extent"), 
    heightmap = elmat, 
    lat = unlist(circle_coords_lat), 
    long = unlist(circle_coords_long), 
    zscale=50, color="red", antialias=FALSE, offset=0, linewidth=5
)

#Generate animation coordinates
camera_path = convert_path_to_animation_coords(extent = attr(localtif,"extent"), 
                                                   heightmap = elmat,
                                                   lat = unlist(circle_coords_lat), 
                                                   long = unlist(circle_coords_long),
                                                   fovs = 80,
                                                   zscale=50, offset=250, frames = 25)
`

**Comment by marcosci** [comment]
Same here on my end, works if WGS84, but not if I reproject to 3031.
![image](https://user-images.githubusercontent.com/10864574/210898659-1e4c0c4c-d433-41fa-98b2-37569b849dfa.png)

**Comment by tylermorganwall** [comment]
Try it again with the latest update from github. I've made some changes to `convert_path_to_animation_coords()` that should result in more robustly generated paths.

**Comment by PJV-Ecu** [comment]
After receiving encouragement by your replies, I realized the foolishness of having placed the initial coordinates backwards (longitude instead of latitude in the code sequence). I took me a while though. Thanks for your support.

**Comment by marcosci** [comment]
Ha, works perfect now 👍
