### ISSUE TITLE
render_high_quality best way to speed up the rendering

### ISSUE THREAD

**Issue by njulemon** [tylermorganwall/rayshader#282]
Hello Tyler,

I am using your wonderful package to render a map of my region. Thanks for this intensive and qualitative work. 

I am wondering if there is any way to speed up the rendering using render_high_quality. 

Is there any possibility to render it using multicore  ?
Not really sure what to check for it. 

Edit : I have been trying to install/reinstall/fresh install. I am able to run it with multicore on MacOS, but not on Ubuntu for higher resolution. 

Thanks for your advices. 

Best

**Comment by tylermorganwall** [comment]
Here are some strategies: 

Lower number of samples, smaller image size (width/height), set min_variance to higher value, ensure sample_method = "sobol_blue".
