### ISSUE TITLE
Update to elevatr: move to sf and terra

### ISSUE THREAD

**Issue by jhollist** [tylermorganwall/rayshader#288]
First, thanks for using elevatr in your package on CRAN.  Really excited that others have found it useful.

This issue is to inform you that there are some big changes coming up shortly with elevatr.  There are all around the archiving of rgdal and rgeos and the associated changes to sp and raster.  I have decided to move entirely to sf and terra and am removing dependencies to rgdal, rgeos, sp, and raster.  This has been implemented in the latest version on the main branch on GitHub (https://github.com/jhollist/elevatr).  I have not completely removed the raster dependency and elevatr is still returning a RasterLayer from get_elev_raster.  This will change in a future release and elevatr will return only sf objects for point elevation and terra SpatRasters for the elevation rasters.  Given this you will need to account for this change in your packages.  

I am planning on sending version 1.0, which still returns RasterLayer, to CRAN in a few days.  At that point I will update the GitHub version to return SpatRasters which should allow you all to test your packages.  I would expect to wait several months before sending the SpatRaster version to CRAN.

**Comment by tylermorganwall** [comment]
rayshader just uses elevatr for some examples and I don't believe there will be any downstream affects--if there are, I will certainly deal with them. Thanks for the issue!
