### ISSUE TITLE
Error in validate_mesh(scene): !any(is.na(normals)) is not TRUE

### ISSUE THREAD

**Issue by adboy316** [tylermorganwall/rayshader#289]
I'm getting the following error whenever I try to use the plot_3d function with a raster that contains NA values:
 
matrix_with_null_values  |> 
  height_shade() |>
  plot_3d(heightmap = matrix_with_null_values, solid=TRUE)
render_snapshot();

Error in validate_mesh(scene): !any(is.na(normals)) is not TRUE

I noticed since version 0.36 this error is also present in the generated docs such as plot_3d.html. I looked at previous branches (0.35) and saw this error does not appear in the that same document. 

I am not sure if this is a bug, or if this is the correct error I'm suppose to be seeing when I use a raster with NA values. But seeing as some of the example in the plot_3d.html are also giving me the same error, and they appear in the docs, I think this may be a bug. 

EDIT: I just installed version 0.35 and this error no longer pops up, so I do think it was introduced with a change you made in 0.36.

**Comment by tylermorganwall** [comment]
I don't believe this is still an issue--if it is, feel free to comment below.
