### ISSUE TITLE
render_snapshot() not working

### ISSUE THREAD

**Issue by ekianjo** [tylermorganwall/rayshader#29]
Hi, thanks a lot for your work on raycaster, this is an amazing package for R!
I have a small issue with render_snapshopt() - R says there is no such function in the package. I tried both with the CRAN version as well as the github version, and I have the same issue. Is there something that I am missing?

**Comment by tylermorganwall** [comment]
Try un-installing the package entirely and re-installing it. It sounds like your installation isn't updated correctly.

**Comment by ekianjo** [comment]
Thanks, you can close this issue!
