### ISSUE TITLE
How to change dpi in render_highquality()?

### ISSUE THREAD

**Issue by dominicroye** [tylermorganwall/rayshader#293]
I am trying to obtain a PNG image with more than 72 dpi. As far as I understand, width and height in `render_highquality() ` define the rgl window in pixels, but what about dpi? I have created 8000 x 8000 px but always with 72 dpi, which is low resolution for printing. I found from another package https://coolbutuseless.github.io/package/devoutrgl/reference/rgldev.html where it is possible for rgl to indicate both width and height in inches and the dpi value.

Thank you

**Comment by tylermorganwall** [comment]
Hello,

Thank you for your question regarding DPI in images created with rayshader. You are correct that width and height parameters in render_highquality() define the pixel dimensions of the image, and DPI is a separate concept, primarily relevant for printing.

For digital images, DPI can be adjusted without changing the actual pixel data. This adjustment alters how the image is intended to be printed or displayed. If you need to set a specific DPI for printing, you can use the magick package in R to modify the DPI metadata of the PNG file.

Here's an example code snippet:

```r
library(magick)

# Load the image
image <- image_read("path/to/your/image.png")

# Set the desired DPI, e.g., 300
image_write(image, "path/to/your/output_image.png", density = 300)
```
