### ISSUE TITLE
render_highquality() leads to Error: Index out of bounds: [index='bump_texname']

### ISSUE THREAD

**Issue by bushushub** [tylermorganwall/rayshader#296]
Hello, when I am trying to use rayshader::render_highquality() (using R, on VSC on Macos) I immediatly get the error: Error: Index out of bounds: [index='bump_texname'].  I could not find any info on this bump_textname index on internet. The package is up to date. 

Here is my code: 

rayshader::plot_gg(
  ggobj = p, 
  # ... (other parameters, plotting works fine)
)

rayshader::render_camera(phi = 85, theta = 0, zoom = 0.99) # render_camera works fine

rayshader::render_highquality(
  filename = "default.png",
  preview = TRUE,
  width = (3000) * .85,
  height = (3000) * .85,
  parallel = TRUE,
  interactive = FALSE
) # The error occurs when running this function

Any idea what the problem stems from?

**Comment by tylermorganwall** [comment]
Update the rayrender and rayvertex packages to their latest versions:

```r
install.packages('rayrender', repos = c('https://tylermorganwall.r-universe.dev', 'https://cloud.r-project.org'))
install.packages('rayvertex', repos = c('https://tylermorganwall.r-universe.dev', 'https://cloud.r-project.org'))

```
