### ISSUE TITLE
dem_01.tif - Where can we download?

### ISSUE THREAD

**Issue by j450h1** [tylermorganwall/rayshader#3]
I'm getting this error:
```
Error in raster::extract(tif_file, raster::extent(tif_file), buffer = 1000) : 
  object 'tif_file' not found
```

I checked your repo,  but couldn't find the file: ```dem_01.tif```

Could you link to this file?

**Comment by tylermorganwall** [comment]
Check out:
http://www.tylermw.com/making-beautiful-maps/

There's a link to the file right below Figure 7
