### ISSUE TITLE
Multi-threading?

### ISSUE THREAD

**Issue by ekianjo** [tylermorganwall/rayshader#31]
I noticed that when rendering, rayshader seems to only use a single thread (or at least a single core). Is there a way, in the future, to support rendering with multiple cores? It would significantly speed up the workload for animations.

**Comment by tylermorganwall** [comment]
Are you referring to `plot_3d()`? That cannot be parallelized, as the rendering is done by the `rgl` package, which is single threaded. The raytracing functions are already parallelized by setting `parallel = TRUE`.

**Comment by tylermorganwall** [comment]
Since this is about rendering (which depends entirely on rgl) and thus I have no control over this request, I am going to close this.
