### ISSUE TITLE
I can't plot correctly with render_snapshot and render_depth functions

### ISSUE THREAD

**Issue by Gualberto-Vannini** [tylermorganwall/rayshader#32]
Hello, 
When I'm trying the test code, for the function render_snapshot() I see into the plot window all black
<img width="1671" alt="schermata 2019-02-23 alle 13 23 22" src="https://user-images.githubusercontent.com/22340454/53286419-74fa4600-376e-11e9-8e3a-45509b14da4f.png">

And trying the test code for the funcion render_depth() my R crashed

<img width="1671" alt="schermata 2019-02-23 alle 13 27 27" src="https://user-images.githubusercontent.com/22340454/53286435-cdc9de80-376e-11e9-87b5-0f4c80408719.png">

My R's version is 
<img width="604" alt="schermata 2019-02-23 alle 13 24 17" src="https://user-images.githubusercontent.com/22340454/53286438-d4f0ec80-376e-11e9-877c-73e934ebced4.png">

Any suggestion?

**Comment by tylermorganwall** [comment]
Set `options(rgl.useNULL = FALSE)` before loading rayshader and try again

**Comment by tylermorganwall** [comment]
See the following twitter conversation:

https://twitter.com/gorggygon/status/1096821006314815489

**Comment by Gualberto-Vannini** [comment]
It works! thank you for your precious attentions!
