### ISSUE TITLE
Feature request: add_water modification

### ISSUE THREAD

**Issue by MirzaCengic** [tylermorganwall/rayshader#34]
Hey Tyler, 

love the work you did here, much appreciated!
I was wondering if it would be possible to have a function to add texture to "air", similarly how add_water adds transparent texture to low areas. So in this way you could have a layer visualizing smog, fog, or clouds. I am working on air pollution data viz, and it would be a great feature to visualize trapped smog in a valley, in addition to "regular" rayshader map.

Thanks

**Comment by tylermorganwall** [comment]
Do you mean to the 3D map, or the 2D? With the 2D map, you can overlay arbitrary data (with transparency) with the `add_overlay()` function.

**Comment by MirzaCengic** [comment]
Yes, to the 3D map, so it can be visualized such as in this picture - [https://github.com/tylermorganwall/rayshader/blob/master/man/figures/README_three-d-labels-1.png](url). Or what might work is to fiddle with the water height settings, and rise it aboveground, and have a texture that would look like transparent fog.

**Comment by tylermorganwall** [comment]
I do have a transparent flat floating data layer feature planned, so that should be able to do what you're interested in,

**Comment by MirzaCengic** [comment]
Great, looking forward to it!
Thanks
