### ISSUE TITLE
Freetype support for Windows builds

### ISSUE THREAD

**Issue by dylanbeaudette** [tylermorganwall/rayshader#36]
Please.

**Comment by tylermorganwall** [comment]
Try installing freetype on windows:

http://gnuwin32.sourceforge.net/packages/freetype.htm

and then building rgl from source:

```r
devtools::install_github("rforge/rgl", subdir="pkg/rgl")
```

**Comment by dylanbeaudette** [comment]
Hey thanks. So this is more of an `rgl` issue then? Sadly, I am trying to make all of this work in a US government IT environment. "You want a compiler? You don't need a compiler!".

Closed?

**Comment by tylermorganwall** [comment]
Oh yes, without the ability to compile it yourself you're SOL. The default version of rgl on Windows does not have Freetype support built-in, but the render_label function should still work, just with the basic built-in font.
