### ISSUE TITLE
geographic axes with integrated scale

### ISSUE THREAD

**Issue by dylanbeaudette** [tylermorganwall/rayshader#37]
Dug this out of the archive. 

Essentially, floating pipes, aligned with grid N,E,S,W that use regular bands of color to communicate equivalent distances. This seems to help with the severe distortion of scale that can happen as the scene is panned / zoomed / tilted. Pipe diameter and distance from the "ground" could be set via argument with default values guessed using grid size and `range(z)`.

![perm_detail1](https://user-images.githubusercontent.com/624277/54058269-3327c180-41aa-11e9-9241-54c91092b306.png)
![om_detail1](https://user-images.githubusercontent.com/624277/54058288-45096480-41aa-11e9-9197-898d231c112c.png)

**Comment by tylermorganwall** [comment]
Added in 7b8c67539a303c224f9178d92198b0c3b824e296
