### ISSUE TITLE
How come the second `plot_3d` doesn't update the image?

### ISSUE THREAD

**Issue by xiaodaigh** [tylermorganwall/rayshader#38]
How do I refresh the `plot_3d` image?

I have set up this simple plot that should show the shadow at 2 diffferent sunangles.

```r
elmat1 = matrix(0, 500, 500)
elmat1[200:400, 200:400] = 971.0

plotlah <- function(elmat1, sunangle1) {
  elmat1 %>%
    sphere_shade %>%
    add_shadow(ray_shade(elmat1,zscale=3,maxsearch = 300, sunangle = sunangle1),0.5) %>%
    plot_3d(elmat1,zscale=10,fov=0,theta=0,zoom=0.75, phi=25, windowsize = c(1000,800))
  render_snapshot()
}

plotlah(elmat1, 45)
plotlah(elmat1, 315) # doesn't update
```
However, once the second `plotlah` doesn't update the image

**Comment by tylermorganwall** [comment]
You need to call `rgl::clear()` after the call to `render_snapshot()`. I'm going to leave this issue open because I'm going to add that as an option to `render_snapshot()`.

**Comment by xiaodaigh** [comment]
You mean `rgl::clear3d()`

**Comment by tylermorganwall** [comment]
Yes, either `rgl::rgl.clear()` or `rgl::clear3d()` works

**Comment by tylermorganwall** [comment]
Added `clear` argument in `render_snapshot()` which closes this issue. See bd33269acbca215c1fdca0cb30a9729fbc8ce0c3
