### ISSUE TITLE
Setting water level in plot_3d

### ISSUE THREAD

**Issue by ixodid198** [tylermorganwall/rayshader#41]
Here is a simple world with the bottom of a lake at 75m and a small rectangular island topping out at 85m. There is 5 m of water in the lake. 

I thought that setting `waterdepth = 80` would create the water around the island. However, I end up with underground water. Why is this?

```
library(magrittr)
library(rayshader)

water <- rep(75, 90)
water_island <- c(rep(75, 30), rep(85, 30), rep(75, 30))

island <- matrix(c(rep(water, 30), rep(water_island, 30), rep(water, 30)),
                 nrow = 90,
                 ncol = 90,
                 byrow = TRUE)

island %>%
  sphere_shade(zscale = 0.1, texture = "imhof1") %>% 
 
  plot_3d(island, zscale = 0.5, fov = 0, theta = -20, phi = 45, windowsize = c(1000, 800), zoom = 0.75,
          water = TRUE, waterdepth = 80, wateralpha = 0.5, watercolor = "lightblue",
          waterlinecolor = "white", waterlinealpha = 0.3)

```

![Screen Shot 2019-04-03 at 10 14 20 PM](https://user-images.githubusercontent.com/12522241/55525147-e971b000-565d-11e9-97c4-643be50d5210.png)

**Comment by ixodid198** [comment]
Solved. I just needed to ensure zscale = 1 in plot_3d.

**Comment by tylermorganwall** [comment]
Thanks for the bug report! This was actually a bug that I fixed in the latest version. See bd33269acbca215c1fdca0cb30a9729fbc8ce0c3

**Comment by tylermorganwall** [comment]
You should be able to specify any `zscale` now.

**Comment by ixodid198** [comment]
Thank-you Tyler. I’m using your very cool package to visualize the flooding of the Toronto Islands in 2017.

law
lpdata.me
lpphoto.me
