### ISSUE TITLE
Perspective support?

### ISSUE THREAD

**Issue by MacTyler** [tylermorganwall/rayshader#42]
Sorry if I am just way off base here,, I don't mean to upset anyone, but it seems that all the rayshader images are rendered where there is no perspective control and parallel lines seem to diverge instead of converge in distance such as this video https://twitter.com/tylermorganwall/status/1118125396199903232 , can there be a feature so you can enable perspective with vanishing points?

**Comment by tylermorganwall** [comment]
Yes, just set the `fov` argument in `plot_3d()` or `render_camera()` to a non-zero number.
