### ISSUE TITLE
add_overlay: Error in `hillshade[, , 1] * (1 - overlay[, , 4])` : non-conformable arrays

### ISSUE THREAD

**Issue by lindsayplatt** [tylermorganwall/rayshader#46]
I've searched for a fix for this, but I just can't seem to find one. The only related [conversation was on Twitter](https://twitter.com/lemuscanovas/status/1074027938524188672) and you said you fixed the issue in a commit around Dec 17, 2018 (which I thought might be [this one](https://github.com/tylermorganwall/rayshader/commit/9374fdedd876aa9b7bef5936456398806e8009ff)). 

I have been trying to debug, but my overlay image passes all the checks and is failing near the end (https://github.com/tylermorganwall/rayshader/blob/master/R/add_overlay.R#L122) and I can't figure out why. Below is my reproducible example.

I am using version `0.10.2`
```
library(rayshader)

elev_file <- "sf-elevation.tif"
download.file("https://github.com/lindsayplatt/makerspace-sandbox/raw/master/rayshader/input/sf-elevation.tif",
              destfile = elev_file, mode = "wb")
elev_img <- raster::raster(elev_file)
elev_matrix <- matrix(
  raster::extract(elev_img, raster::extent(elev_img), buffer = 1000), 
  nrow = nrow(elev_img), ncol = ncol(elev_img)
)

img_file <- "overlay.png"
download.file("https://github.com/lindsayplatt/makerspace-sandbox/raw/master/rayshader/input/overlay.png",
              destfile = img_file, mode = "wb")
overlay_img <- png::readPNG(img_file)

# Without overlay works
elev_matrix %>%
  sphere_shade(texture = "imhof1") %>%
  plot_3d(elev_matrix)

# With overlay fails
elev_matrix %>%
  sphere_shade(texture = "imhof1") %>%
  add_overlay(overlay_img, alphalayer = 0.5) %>%
  plot_3d(elev_matrix)
```

**Comment by tylermorganwall** [comment]
The overlay needs to be the same dimensions as the hillshade (in this case, 400x400). I inserted some extra code to show how you can resize the overlay using base R:

```r

elev_file <- "sf-elevation.tif"
download.file("https://github.com/lindsayplatt/makerspace-sandbox/raw/master/rayshader/input/sf-elevation.tif",
              destfile = elev_file, mode = "wb")
elev_img <- raster::raster(elev_file)
elev_matrix <- matrix(
  raster::extract(elev_img, raster::extent(elev_img), buffer = 1000), 
  nrow = nrow(elev_img), ncol = ncol(elev_img)
)

img_file <- "overlay.png"
download.file("https://github.com/lindsayplatt/makerspace-sandbox/raw/master/rayshader/input/overlay.png",
              destfile = img_file, mode = "wb")
overlay_img <- png::readPNG(img_file)

resized_overlay_file = paste0(tempfile(),".png")
grDevices::png(filename = resized_overlay_file, width = dim(elev_matrix)[1], height = dim(elev_matrix)[2])
par(mar = c(0,0,0,0))
plot(as.raster(overlay_img))
dev.off()
overlay_img = png::readPNG(resized_overlay_file)

# Without overlay works
elev_matrix %>%
  sphere_shade(texture = "imhof1") %>%
  plot_3d(elev_matrix)

# With overlay fails
elev_matrix %>%
  sphere_shade(texture = "imhof1") %>%
  add_overlay(overlay_img, alphalayer = 0.5) %>%
  plot_3d(elev_matrix)

```
![overlay](https://user-images.githubusercontent.com/297609/60147518-b68e1280-979b-11e9-9dc4-e0bb775eaed8.png)

I will include this code built-in to the next version to automatically resize the overlay and display a warning so you won't have to run this code yourself. But until then, this should work.

**Comment by lindsayplatt** [comment]
Excellent! I thought I had pulled down an image of that exact size, but I suppose not. Automatically resizing with a warning would be awesome. Thanks! ✔️

**Comment by tylermorganwall** [comment]
Fixed in 1954bc85c151f536b25058b6152bb09bdc67c54b

**Comment by nitschkematthew** [comment]
Hi @tylermorganwall @lindsayplatt . I think I am encountering the same issue with overlays. I have installed the latest version of rayshader from github (0.12.0). When the hillshade matrix dimensions are evaluated against the overlay dimensions it seems that the hillshade has been transposed. I have tried the overlay in both orientations and have double checked the dimensions.

- elmat (https://www.dropbox.com/s/cznth371x05bsmn/li_20m.txt?dl=0)
- satellite overlay (https://www.dropbox.com/s/7zx9xx6cl9bqr04/Sentinel-2%20L2A%20from%202019-07-31.tiff?dl=0)

```
library(rayshader)
library(rgdal)
library(raster)
library(png)
library(EBImage)
```

```
# Load in satellite image and get the CRS
sentinel <- stack("Sentinel-2 L2A from 2019-07-31.tiff")
sentinelcrs <- sentinel@crs@projargs

# Load in bathymetry data as raster, and convert to same CRS as satellite image
lizbath <- raster("li_20m.txt")
proj4string(lizbath) <- CRS("+init=epsg:28355")
lizbath_p <- projectRaster(lizbath, crs = sentinelcrs)

# Now that CRS are matching, crop satellite image to match extent of bathymetry
sentinel_c <- crop(sentinel, lizbath_p)

# Read in bathymetry table as matrix and transpose for rayshader
elmat <- t(as.matrix(read.table("li_20m.txt", header = FALSE, sep = " ", skip = 6)))
elmat[elmat == -9999] <- -40.24729 # Replace missing values
elmat[is.na(elmat)] <- -40.24729 # Replace NAs

# Save the cropped satellite image with dimensions matching the baythmetry matrix
plotRGB(sentinel_c)
dev.print(png, "overlay.png", width = dim(elmat)[1], height = dim(elmat)[2], units = "px")

# Read in the overlay and transpose it so that dimensions match elmat
overlay <- readPNG("overlay.png")
overlay_trans <- EBImage::transpose(overlay)

# This works
elmat %>%
  sphere_shade(texture = "imhof4") %>%
    plot_3d(elmat,
            zscale = 10,
            water = TRUE,
            waterdepth = 0,
            wateralpha = 0.5,
            watercolor = "blue")

# Adding overlay fails with error
elmat %>%
  sphere_shade(texture = "imhof4") %>%
    add_overlay(overlay_trans, alphacolor = .9) %>%
    plot_3d(elmat,
            zscale = 10,
            water = TRUE,
            waterdepth = 0,
            wateralpha = 0.5,
            watercolor = "blue")

# Error Message: Overlay doesn't match dimension of hillshade--resizing to matchError in alphalayer1[j, i] : subscript out of bounds
```
Now lets do some testing to make sure that the dimensions are correct
```
# Create a hillshade to test dimensions
sphere_test <- elmat %>%
  sphere_shade(texture = "imhof4")

# Test for unequal dimensions
dim(elmat)[1:2] == dim(overlay_trans)[1:2] # Evaluates to TRUE TRUE
dim(elmat)[1:2] == dim(sphere_test)[1:2] # Evaluates to FALSE FALSE
dim(overlay_trans)[1:2] == dim(sphere_test)[1:2] # Evaluates to FALSE FALSE
```

**Comment by Debobrata-Sadhukhan** [comment]
Warning message:
In make_shadow(heightmap, shadowdepth, shadowwidth, background,  :
  `magick` package required for smooth shadow--using basic shadow instead.
> Sys.sleep(0.2)
> render_snapshot()
> render_snapshot()
> #And we can add a raytraced layer from that sun direction as well:
> elmat %>%
+   sphere_shade(texture = "desert") %>%
+   add_water(detect_water(elmat), color = "desert") %>%
+   add_shadow(ray_shade(elmat), 0.5) %>%
+   plot_map()
Error in hillshade[, , 1] * scales::rescale(shadowmap, c(max_darken, 1)) : 
  non-conformable arrays


Getting this error please help me how can I fix this?
