### ISSUE TITLE
Can't install rayshader

### ISSUE THREAD

**Issue by NeilKaye** [tylermorganwall/rayshader#47]
I've tried installing rayshader on both windows and linux without success:

On Linux I get:

ERROR: configuration failed for package ‘av’
* removing ‘/net/home/h05/hadnk/R/x86_64-pc-linux-gnu-library/3.6/av’
Error in i.p(...) : 
  (converted from warning) installation of package ‘av’ had non-zero exit status

On windows I get when trying to install from devtools:

 devtools::install_github("tylermorganwall/rayshader")
Error in curl::curl_fetch_memory(url, handle = h) : 
  Timeout was reached: Connection timed out after 10000 milliseconds

By downlading zip and trying to install locally I get:
> utils:::menuInstallLocal()
> require(rayshader)
Loading required package: rayshader
Warning message:

In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘rayshader’
>

**Comment by tylermorganwall** [comment]
Have you tried installing the "av" package and then installing rayshader?

**Comment by NeilKaye** [comment]
I did try but I'm wondering if it is something to do with ffmpeg as I think
I have version 2.8 because it is fixed to a rhel7 build at work. I will try
again tomorrow as I mostly use ggplot so this would be great if I can get
it to work.

**Comment by adamBirenbaum** [comment]
I ran into the same issue.  In my case (Ubuntu 18.04) for 'av' to install successfully and therefore 'rayshader', I just needed to install the 'libavfilter' library.
In the terminal:

`sudo apt-get update`
`sudo apt-get install -y libavfilter-dev`

**Comment by NeilKaye** [comment]
Sounds promising I will try that
