### ISSUE TITLE
Failed Mac install

### ISSUE THREAD

**Issue by sethmund** [tylermorganwall/rayshader#5]
> devtools::install_github("tylermorganwall/rayshader")
    Downloading GitHub repo tylermorganwall/rayshader@master
    from URL https://api.github.com/repos/tylermorganwall/rayshader/zipball/master
    Installing rayshader
    '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
    '/private/var/folders/yh/q7331v716lbdvw4kjzl5m0g80000gp/T/RtmpNiBjr0/devtools1a7f7364f175/tylermorganwall-rayshader-c862fe1'  \
    --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library' --install-tests 
    
    * installing *source* package ‘rayshader’ ...
    ** libs
    clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/progress/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
    clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/progress/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c calculate_normal.cpp -o calculate_normal.o
    clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/progress/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c construct_matrix.cpp -o construct_matrix.o
    clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/progress/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c find_groups.cpp -o find_groups.o
    clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/progress/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c interpolate_color.cpp -o interpolate_color.o
    interpolate_color.cpp:19:16: warning: expression result unused [-Wunused-value]
    colormat[i,j] = bilinear_interp_colors(color_sw, color_nw, color_sw, color_nw,
                                           ^
                                             1 warning generated.
                                           clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/progress/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c lambshade.cpp -o lambshade.o
                                           clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/progress/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c rayshade.cpp -o rayshade.o
                                           clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/progress/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c rayshade_multicore.cpp -o rayshade_multicore.o
                                           clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o rayshader.so RcppExports.o calculate_normal.o construct_matrix.o find_groups.o interpolate_color.o lambshade.o rayshade.o rayshade_multicore.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
                                           installing to /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rayshader/libs
                                           ** R
                                           ** byte-compile and prepare package for lazy loading
                                           Error in dyn.load(file, DLLpath = DLLpath, ...) : 
                                             unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/imager/libs/imager.so':
                                             dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/imager/libs/imager.so, 6): Library not loaded: /opt/X11/lib/libX11.6.dylib
                                           Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/imager/libs/imager.so
                                           Reason: image not found
                                           ERROR: lazy loading failed for package ‘rayshader’
                                           * removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rayshader’
                                           Installation failed: Command failed (1)

**Comment by sethmund** [comment]
I was on 3.4 then updated to 3.5.1. same deal both times.

**Comment by tylermorganwall** [comment]
I believe you need to install XQuartz--go to this website and see if that fixes your issue.

https://www.xquartz.org/

**Comment by tylermorganwall** [comment]
I had someone else contact me about this exact issue and installing XQuartz did fix it for them--I am going to close this issue.

**Comment by lgellis** [comment]
Just want to comment that I just encountered this and your fix still resolves the issue @tylermorganwall.  Thanks!

**Comment by tylermorganwall** [comment]
Glad it helped!

**Comment by darh78** [comment]
> I believe you need to install XQuartz--go to this website and see if that fixes your issue.
> 
> https://www.xquartz.org/

The workaround above also solved the same issue to me. Thanks.

**Comment by ries9112** [comment]
Hi @tylermorganwall I have a related question. Any guidance you could give in terms of installing XQuartz on a GitHub Actions CI process? 

I am running the following command when setting up the macOS machine before running any R code:
```
brew cask install xquartz
```

When I install rayshader I am getting an error showing I don't have it installed:
```
Error: Error: .onLoad failed in loadNamespace() for 'rgl', details:
  call: NULL
  error: X11 not found; XQuartz (from www.xquartz.org) is required to run rgl.
Execution halted
ERROR: lazy loading failed for package ‘rayshader’
* removing ‘/Users/runner/work/cryptocurrencyresearch-org/cryptocurrencyresearch-org/renv/library/R-4.0/x86_64-apple-darwin17.0/rayshader’
Error: Error: Failed to install 'rayshader' from GitHub:
  (converted from warning) installation of package ‘/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//RtmpGpDzTF/file39376fbf46ba/rayshader_0.19.4.tar.gz’ had non-zero exit status
```

Would you have any thoughts on the command for a macOS (or any other) machine to install XQuartz rather than using the website?

You can find the GitHub CI Action run here: https://github.com/ries9112/cryptocurrencyresearch-org/runs/1300319107
And the .yaml file that controls the action with the XQuartz install followed by package install: https://github.com/ries9112/cryptocurrencyresearch-org/commit/92f0eee602211c7b599a3a6fde3d90d974c03a9a#

Thank you for all your amazing work and no worries if you wouldn't know the answer here, but might be useful for others in the future if you do.

**Comment by BlakeBeus** [comment]
Installing xquartz didn't entirely fix this for me on MacOS with R 4.x

Following the steps to properly install the development chain for R on MacOS here worked for me though: https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/
