### ISSUE TITLE
plot_gg issue

### ISSUE THREAD

**Issue by kunalbali** [tylermorganwall/rayshader#50]
Today I installed 
remotes::install_github("tylermorganwall/rayshader")
library(rayshader)
library(ggplot2)
library(sf)
library(viridis)

But still
could not find function "plot_gg"

any suggestion on that.

Thank You

**Comment by tylermorganwall** [comment]
Try uninstalling and reinstalling the package--the plot_gg() function is there, I promise :)

**Comment by Shaunofthedead19** [comment]
Hi @tylermorganwall , the issue still exists....I installed:
devtools::install_github("tylermorganwall/rayshader")

but could not find "plot_gg" function.

I reinstalled the package as well.

Any suggestions?

Thank You
