### ISSUE TITLE
Axis titles are turned to 3d objects

### ISSUE THREAD

**Issue by lavik17** [tylermorganwall/rayshader#55]
I am creating a heatmap using the following code:
```
gg <- tib_long %>%
  group_by(Func, variable) %>%
  ggplot(aes(x=variable, y=Func)) + 
  geom_tile(aes(fill = value), colour = "white") + 
  scale_fill_gradient(low = "white", high = "red")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank())
```
and plotting with: 
```
plot_gg(gg, width=5, height=5, multicore=TRUE, raytrace = TRUE, shadow_intensity = 0.2, scale = 200)
```
The y axis of the plot is turned into a 3d-object (lifter to the maximum height, making the text unreadble.

**Comment by gustavo-etal** [comment]
Please remove me from this list
Thanks

**Comment by tylermorganwall** [comment]
I have a fix incoming for this issue.

**Comment by tylermorganwall** [comment]
This is fixed in c94bb232b0d21e7912578377af711fdb8af24f4a

**Comment by balgan** [comment]
Post this patch, my render has now become fully flat

![rayshader-flat](https://user-images.githubusercontent.com/1078950/60666533-8ca5b180-9e67-11e9-9ed6-d76305d15735.png)

It used to look like this before patch:

![D-inyPTW4AAarFm](https://user-images.githubusercontent.com/1078950/60666609-b8289c00-9e67-11e9-969d-f71e1e41d92e.jpg)

Let me know if anything else is needed @tylermorganwall

**Comment by tylermorganwall** [comment]
You will need to provide me with a reproducible example so I can debug the issue. Replace your dataset with mtcars but keep all of your theme settings and post the code.
