### ISSUE TITLE
Issue with installation - processx_exec

### ISSUE THREAD

**Issue by QuangVanBui** [tylermorganwall/rayshader#56]
Hi there,

Hoping you might be able to help with an installation error.

When running devtools::install_github("tylermorganwall/rayshader") I receiving the following error:

Incorrect number of arguments (16), expecting 14 for 'processx_exec' 

Any help would be much appreciated :)

Cheers,
Quang

**Comment by tylermorganwall** [comment]
Install the following two packages and try again (I assume you're on windows):

```r
install.packages(c("processx","callr"))
```

**Comment by QuangVanBui** [comment]
Yes, I'm working on Windows. I've tried this but still no luck.

This is exactly what appears in the trackback. 

Error: Failed to install 'rayshader' from GitHub: Incorrect number of arguments (16), expecting 14 for 'processx_exec'

7.
stop(remote_install_error(remotes[[i]], e))
6.
value[[3L]](cond)
5.
tryCatchOne(expr, names, parentenv, handlers[[1L]])
4.
tryCatchList(expr, classes, parentenv, handlers)
3.
tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) { stop(remote_install_error(remotes[[i]], e)) })
2.
install_remotes(remotes, auth_token = auth_token, host = host, dependencies = dependencies, upgrade = upgrade, force = force, quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, build_vignettes = build_vignettes, repos = repos, type = type, ...
1.
devtools::install_github("tylermorganwall/rayshader")

**Comment by tylermorganwall** [comment]
Try uninstalling rayshader, processx, and callr, restart R, and then reinstall the latter two from the CRAN and then try installing rayshader again.

**Comment by QuangVanBui** [comment]
It has worked! Thank you very much, Tyler!
