### ISSUE TITLE
How to increase render_camera orbiting time

### ISSUE THREAD

**Issue by longhaivo** [tylermorganwall/rayshader#57]
Hi All,
I would like to know if there is a way to increase the rotation speed and rotation time of objects when using the 'render_movie' function. As indicated in the help file, by default it is 12 secs and I want to change it to say 60 secs. I've also noticed that the base function of 'render_movie' is 'av::av_capture_graphics', but not quite sure how to adjust it to get the desired result. Another parameter of interest is the zoom level.
Here is an example code
`library(rayshader);
library(ggplot2);
library(viridis);
library(sf);
nc = st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE);
gg_nc = ggplot(nc) +
  geom_sf(aes(fill = AREA)) +
  scale_fill_viridis("Area") +
  ggtitle("Area of counties in North Carolina") +
  theme_bw();
gg_nc;
plot_gg(gg_nc, multicore = TRUE, width = 6 ,height=2.7, fov = 70);
render_movie(filename = tempfile(), type = 'orbit', 
             frames = 60,  phi = 40, zoom = 1)  `
which results in this speedy [rotated map](https://drive.google.com/file/d/1_KlHNF63KGJl7-pX1ybXD67Qi5k9FzcN/view?usp=sharing) that only lasts for 2 secs.
Any suggestions are appreciated.

Regards,
Long

**Comment by tylermorganwall** [comment]
The duration is determined by the ‘frames’ argument divided by the ‘fps’ argument. To make the video longer, increase the number of frames. If you want a 60s long video at 30fps, that means use 1800 frames.
