### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by marcosci** [tylermorganwall/rayshader#6]
Hey Tyler -  awesome package :-)

I am trying to figure out how to use it with one of my packages and while playing around with it,
I thought it would probably be nice to have a test dataset for quick exploration of rayshader included in your package? Maybe one of the example datasets you show in the README.

Cheers,
Marco

**Comment by tylermorganwall** [comment]
Good idea--I'll include a few small USGS-derived datasets (as their maps are in the public domain) with an update.

**Comment by tylermorganwall** [comment]
I added an example dataset `montereybay` to the latest update--enjoy.

**Comment by marcosci** [comment]
thanks a lot! again, keep up the good work, really enjoying this!
