### ISSUE TITLE
how to make a moving ggplot and save into gif

### ISSUE THREAD

**Issue by TonyFly3000** [tylermorganwall/rayshader#62]
how to make a moving ggplot and save into gif ?

I try this ,but the plot does not move automatically :

library(rayshader)
library(ggplot2)
gg = ggplot(diamonds, aes(x, depth)) +
  stat_density_2d(aes(fill = stat(nlevel)), 
                  geom = "polygon",
                  n = 100,bins = 10,contour = TRUE) +
  facet_wrap(clarity~.) +
  scale_fill_viridis_c(option = "A")
plot_gg(gg,multicore=TRUE,width=5,height=5,scale=250)

render_camera()

**Comment by tylermorganwall** [comment]
render_movie() is the function you are looking for.

**Comment by dieghernan** [comment]
See #150 for an approach that converts the movie onto a gif with `magick` package
