### ISSUE TITLE
ggplot 3D printing y axis,x axis and title

### ISSUE THREAD

**Issue by TonyFly3000** [tylermorganwall/rayshader#64]
I try to print out the 3D ggplot . I have saved it into stl file. 

But is there any way to display the y axis, x axis and title ? 

I think y axis; x axis and title in ggplot are not in 3D ? 

--------------------------------------
library(rayshader)
library(ggplot2)

mtplot = ggplot(mtcars) + 
  geom_point(aes(x = mpg, y = disp, color = cyl)) + 
  scale_color_continuous(limits = c(0, 8))

plot_gg(mtplot, width = 3, height = 2.5, scale = 300, multicore = TRUE, windowsize = c(1200, 960),
        fov = 70,theta = 330, phi = 40)

save_3dprint("mtcars_3d.stl", maxwidth = 100, unit = "mm")

**Comment by tylermorganwall** [comment]
No, not currently. The STL file just contains the geometry, not the texture on the surface of the 3D model.
