### ISSUE TITLE
render_movie fails if height not divisible by 2

### ISSUE THREAD

**Issue by dk-forestry** [tylermorganwall/rayshader#67]
I tried to export a full-screen animation on Windows 10. This failed for me:

`filename_movie = tempfile()`

`montereybay %>%
sphere_shade(texture="imhof1") %>%
plot_3d(montereybay, windowsize = c(1980, 1080), zscale=50, water = TRUE, watercolor="imhof1", waterlinecolor="white", waterlinealpha=0.5)`

`render_movie(filename = filename_movie, frames = 10)`

Error message:
`height not divisible by 2 (1924x1061)`
`Error: FFMPEG error in 'avcodec_open2': Generic error in an external library`

It seems that 

1. the plot window got automatically rescaled to 1924x1061 (my display size: 1980x1080), and 
2. FFMPEG cannot export uneven dimensions. This can be confirmed by using arbitrary uneven dimensions (e.g. `windowsize = c(100, 101)`

It's probably easiest to fix 2). Here's a possible modification of `render_movie` to fix the problem:

Old:
`...`
`windowsize = rgl::par3d()$viewport`
`...`

New:
`...`
`windowsize = rgl::par3d()$viewport`
`windowsize['width'] <- ceiling(windowsize['width']) - ceiling(windowsize['width']) %% 2`
`windowsize['height'] <- ceiling(windowsize['height']) - ceiling(windowsize['height']) %% 2`
`rgl::par3d(windowRect = windowsize)`
`...`

**Comment by tylermorganwall** [comment]
Download and install the latest version (0.11.5) of rayshader from github. I fixed this problem in 0.11.3 (see 8144c990838a69d4565753407aadd44c2ec99be5)

**Comment by dk-forestry** [comment]
Actually, I already had version 0.11.5 installed, but nevertheless run into the error. I can replicate the error when I manually try to create a movie with

`av::av_encode_video(png_files, output = filename, framerate = fps, vfilter = "scale=-2:-2")`

Changing `vfilter = "scale=-2:-2"` to `vfilter = "scale=2:-2"` (no `-` in front of the first `2`) fixes the error for me.

**Comment by tylermorganwall** [comment]
This is now fixed in the latest version fb228118df68829878bf12e3a01cf7db302ec52b
