### ISSUE TITLE
R session Aborted

### ISSUE THREAD

**Issue by zluscher** [tylermorganwall/rayshader#68]
Installed:
R. Version 3.6.1
Rtools 3.3
Rstudio 64 bit windows

Then install missing 'rgl'

I try to call the library(rayshader)
But the R session Aborts, R encountered fatal error

**Comment by tylermorganwall** [comment]
Try completely removing the rgl package (you may have to find your R library and delete it manually on windows) and then reinstall. This sounds more like a local R installation issue than a rayshader issue.

**Comment by tylermorganwall** [comment]
Closing issue as local installation problem (if you are still having this issue, comment here and we can work it out).

**Comment by ppramg** [comment]
Hello,
I face the same issue. I installed latest versions of Rstudio, Rtools and R, but as soon as I call the library (rayshader), R session aborts...
I tried to install from cran and from your github, and I tried to completely remove the rgl package but nothing helped...
I f you have a suggestion to fix that I would be very grateful !
Thanks for your great work by the way.
