### ISSUE TITLE
Library not loaded: /opt/X11/lib/libX11.6.dylib

### ISSUE THREAD

**Issue by amilyjusttoday** [tylermorganwall/rayshader#71]
library(rayshader)
错误: package or namespace load failed for ‘rayshader’ in dyn.load(file, DLLpath = DLLpath, ...):
 无法载入共享目标对象‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/imager/libs/imager.so’：:
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/imager/libs/imager.so, 6): Library not loaded: /opt/X11/lib/libX11.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/imager/libs/imager.so
  Reason: image not found

**Comment by tylermorganwall** [comment]
Do you have the X11 window server installed?

**Comment by amilyjusttoday** [comment]
I installed XQuartz and problem solved, thanks
