### ISSUE TITLE
Unable to embed plot_gg dynamic outputs into rglwidgets in Shiny

### ISSUE THREAD

**Issue by Norsesforcourses** [tylermorganwall/rayshader#78]
Apologies if my difficulties are the result of naivety or my lack of experience with rglwidgets in Shiny. I can use plot_gg in Shiny in its 'simplest' use case, where I allow an external x11 window to spawn and embed static shots using render_snapshot:

```
library(shiny)
library(tidyverse)
library(rgl)
library(rayshader)
library(viridis)
library(isoband)

ui <- fluidPage(
  hr("how do we getplot_gg to work at all with rglwidget? This basic code obviously works."),

  plotOutput("plot",  width = 800, height = 600)
)

server <- (function(input, output) {

  ggdiamonds <- reactive({
    diamonds %>%
      filter(clarity == "VS1") %>%
    ggplot() +
      stat_density_2d(aes(x = x, y = depth, fill = stat(nlevel)), 
                  geom = "polygon", n = 100, bins = 10, contour = TRUE) +
      scale_fill_viridis_c(option = "A")
  })
  
   output$plot <- renderPlot({
     plot_gg(ggdiamonds(), width = 5, height = 5, multicore = TRUE, scale = 250, 
        zoom = 0.7, theta = 10, phi = 30, windowsize = c(800, 800))
  render_snapshot(clear = FALSE)
   })
  
})

shinyApp(ui = ui, server = server)
```

But if I try to embed the interactive window into a rglwidgetOutput, I *still* get the external x11 popup. My CPU gets hammered, the external window interaction is extremely slow, and nothing embeds. Serious warning, this code has resulted in me having to end processes to recover things:

```
library(shiny)
library(tidyverse)
library(rgl)
library(rayshader)
library(viridis)
library(isoband)

ui <- fluidPage(
  hr("how do we getplot_gg to work at all with rglwidget? This code hammers my processor, pops up the (much slower) external x11 window, doesn't embed a widget."),

  rglwidgetOutput("plot",  width = 800, height = 600)
)

server <- (function(input, output) {

  ggdiamonds <- reactive({
    diamonds %>%
      filter(clarity == "VS1") %>%
    ggplot() +
      stat_density_2d(aes(x = x, y = depth, fill = stat(nlevel)), 
                  geom = "polygon", n = 100, bins = 10, contour = TRUE) +
      scale_fill_viridis_c(option = "A")
  })
  
   output$plot <- renderRglwidget({
     plot_gg(ggdiamonds(), width = 5, height = 5, multicore = TRUE, scale = 250, 
        zoom = 0.7, theta = 10, phi = 30, windowsize = c(800, 800))
     rglwidget()
   })
  
})

shinyApp(ui = ui, server = server)
```

What is catastrophically wrong with my approach here?

The genesis of this was that it seems that Shiny Server has some issues with external x11 windows which I was trying to avoid. I don't know if this approach would help at all, and I still haven't found out, because I couldn't even get it to work. Little help?

**Comment by tylermorganwall** [comment]
Set `options(rgl.useNULL = TRUE)` before calling `library(rgl)` and try again. It will no longer open the X11 window, but you should still be able to call `rglwidget()`.

**Comment by Norsesforcourses** [comment]
Thank you for the prompt response!

Just to let you know, this did lead to a change in behavior, but since I am
working behind a corporate firewall, the behavior was Rstudio asking for
firewall access. Presumably this is related to it reaching out through a
particular port for rglwidget (? showing my ignorance of such matters, but
come on, I'm a materials scientist) which firewall is holding closed.

I will update once I can have the gatekeepers circumvent this issue for me.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Norsesforcourses** [comment]
OK. After dealing with the firewall issue, running from RStudio leans heavily on my CPU (probably more heavily than the simple code), does not show a widget or any kind of display: no popup (half way there?).

My experience has been that sometimes the RStudio window won't show a rglwidget. After some processing time I get the console output:

```Loading required namespace: rmarkdown ```

But never see a widget. Going to webpage view does not help in this case, although it has helped in the past when I have been unable to see a widget.

Does this example, with the options line added, reproduce correctly for you, or do I simply have some rglwidget implementation problem (that obviously isn't your domain unless you want it to be).

**Comment by tylermorganwall** [comment]
It works, you just have to give it time--creating the rglwidget takes a while, especially when you increase the size of the ggplot (with the width and height options). Set the width and height to 3 and give it a minute or two. 

Example output:
![2019-09-20_17-28-11](https://user-images.githubusercontent.com/297609/65359989-29a4fa80-dbcc-11e9-8b1b-61e00db5e8f9.jpg)

**Comment by Norsesforcourses** [comment]
OK, thank you. Reducing the size got me there. All right. I'll assess those
performance impacts and take it from there.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
