### ISSUE TITLE
add_overlay: overlay dimensions passed to resize in incorrect order

### ISSUE THREAD

**Issue by nitschkematthew** [tylermorganwall/rayshader#79]
https://github.com/tylermorganwall/rayshader/blob/f3b284e378d8221fd7e796b9464deb628437bec7/R/add_overlay.R#L54

I think the dims are passed in the incorrect order. This breaks my overlay. I describe the issue here 

https://github.com/tylermorganwall/rayshader/issues/46#issuecomment-517912781

**Comment by tylermorganwall** [comment]
I don't believe this is still an issue—I go into detail on this blog post (https://www.tylermw.com/a-step-by-step-guide-to-making-3d-maps-with-satellite-imagery-in-r/) on how to add satellite overlays to rayshader maps.
