### ISSUE TITLE
Error in `add watermap`

### ISSUE THREAD

**Issue by mikejohnson51** [tylermorganwall/rayshader#8]
Hi Tyler, 

I ran into an interesting error trying to add a watermap created using the NHD to an elevation hillshade that I cant seem to fix (it appears it might be a bug). I have attached an example and the data I use can be found [here](https://drive.google.com/open?id=1lLjfrd_jPX3sNeDMS64ccm8UFzYmT0tm)

```r
library(raster)
library(rgdal)
library(rayshader)

#Read in data
elev = raster("./rayshader_issue/elev.tif")
river = rgdal::readOGR("./rayshader_issue/nhd.shp")
#Convert NHD to SpatialLines
river = as(river, "SpatialLines")

# Create Raster with equal extent, dim and res to elev with all values = 0 
r = raster()
extent(r) = extent(elev)
dim(r) = dim(elev)
res(r) = res(elev)
crs(r) = crs(elev)
values(r) = 0

# Rasterize rivers to new raster;  set water to 1 and all else to 0
rr = rasterize(river, r)
values(rr)[is.na(values(rr))] = 0
values(rr)[values(rr) != 0] = 1

rr
elev
```

```r
> rr
class       : RasterLayer 
dimensions  : 262, 336, 88032  (nrow, ncol, ncell)
resolution  : 0.0002777778, 0.0002777778  (x, y)
extent      : -104.8681, -104.7747, 38.7975, 38.87028  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +ellps=GRS80 +no_defs 
data source : in memory
names       : layer 
values      : 0, 1  (min, max)

> elev
class       : RasterLayer 
dimensions  : 262, 336, 88032  (nrow, ncol, ncell)
resolution  : 0.0002777778, 0.0002777778  (x, y)
extent      : -104.8681, -104.7747, 38.7975, 38.87028  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs 
data source : /Users/mikejohnson/Documents/GitHub/rayshader_issue/tyler/elev.tif 
names       : elev 
values      : 1773.827, 2000.999  (min, max)
```

```r 
# Convert water and elevation rasters to rayshader style matrix
water = matrix(raster::extract(rr,raster::extent(rr),buffer=1000),
               nrow=ncol(rr),ncol=nrow(rr))
elevmat = matrix(raster::extract(elev,raster::extent(elev),buffer=1000),
               nrow=ncol(elev),ncol=nrow(elev))

#check dims
dim(water) == dim(elevmat)
```
```r
[1] TRUE TRUE
```

```r
# Rayshade!!
sphere_shade(elevmat, texture = "imhof1") %>% 
add_water(water, color="desert") %>% 
plot_map()
```
```r
Error in add_water(., water, color = "desert") :                                   
  `hillshade` and `watermap` dimensions must be the same; hillshade is 260x334, 
watermap is 262x336
```
Just to be sure:

```r
dim(elevmat)
dim(water) 
```
```r
> dim(elevmat)
[1] 336 262
> dim(water)
[1] 336 262
```
Have you found any way to avoid this / do you know were I am going wrong?

Thanks!

Mike

**Comment by tylermorganwall** [comment]
Hi Mike,
Set `remove_edges = FALSE` in sphere_shade(). By default, rayshader slices off the edges because there are usually ugly edge artifacts there. I'm actually going to change this behavior on the next release so it shouldn't be a problem, but the above argument should fix it.
Tyler

**Comment by mikejohnson51** [comment]
Hi Tyler, 

Fantastic, that get the plot running. Any idea why the water plot would appear flipped vertically (bottom is at the top but left and right are correct)?

Plotting with straight raster::plot shows them correct and I am running this:

```r
# Convert water and elevation rasters to rayshader style matrix
water = matrix(raster::extract(rr,raster::extent(rr),buffer=1000),
               nrow=ncol(rr),ncol=nrow(rr))
elevmat = matrix(raster::extract(elev,raster::extent(elev),buffer=1000),
               nrow=ncol(elev),ncol=nrow(elev))
```

I've tried some variation of rev() and t() to get the matrix flipped but cant seem to get it to hold in the plot.

I really appreciate the help and will send you an image once done!

Mike

**Comment by mikejohnson51** [comment]
It solved with this!
```r
water =   matrix(values(rr),
               nrow=ncol(rr),ncol=nrow(rr))

water1 = apply(water, 2, rev)
water2 = apply(t(water1),2,rev)
water2 = apply(t(water2),2,rev)
```

I am sure there is an easier way, if you now of a quick one that would be great otherwise this can be closed. 

Again, great work!
Mike

**Comment by tylermorganwall** [comment]
That is definitely the shortest way to do it! You can also do something like water[nrow(water):1,] or water[,ncol(water):1], depending on the direction you want to flip.

**Comment by mikejohnson51** [comment]
As promised: Here is a 1 degree by 1 degree NED tile overlaid with the NHD waterbodies and flow lines. The goal is to get a basemap like this for all of California so if you have any suggestions on appearance they would be welcome!

[image](https://drive.google.com/open?id=12cjTaXafkvh3ljApS6pX2YRDBbvK56mh)

**Comment by tylermorganwall** [comment]
Love the map! If you want a little more color, lower the zscale parameter slightly in sphere_shade. It will pull colors from further out in the texture map. Looking forward to seeing more

**Comment by mikejohnson51** [comment]
Hey Tyler, 

Its working great - I added a few images made with your package to the carousel on this site... I'll mess with the zscale a bit to see what happens...

Thanks again!

**Comment by tylermorganwall** [comment]
Glad to hear--to which site do you refer?

**Comment by mikejohnson51** [comment]
Sorry! [here it is](https://mikejohnson51.github.io/FlowFinder/). Image 3 and 5

**Comment by tylermorganwall** [comment]
Great stuff! Really fantastic work especially on the 3rd image.

**Comment by mikejohnson51** [comment]
Thanks Tyler, 

I'm glad you like it. If you have any interest in adding the NHD water polygon generator to your package feel free! I can point you to the right functions and they are fast (require a dependency on sf). None are supported in a CRAN package so you if easiest you can just copy them in... if not no worries either!

Mike

**Comment by tylermorganwall** [comment]
Post the code! Data import and manipulation is one of the trickiest parts of this work for most people. It would be good to have some examples combining rayshader with external libraries.

**Comment by mikejohnson51** [comment]
Most of the code for getting data is in this package [HydroData](https://github.com/mikejohnson51/HydroData)

In particular, **findNED()** will get elevation data, **findNHD()** will get the river networks, and **findWaterbodies()** will find local waterbodies.

**findWaterPoly()** combines all water features into a single polygon by giving streams a thickness based on their order.

The package uses [AOI](https://github.com/mikejohnson51/AOI) to define regions. So you can get something like: 

```
UCSB = AOI::getAOI(list(UCSB,10,10) %>% findNED() %>% findWaterPoly()
```

Then your elevation  raster would be:

```
UCSB$NED
```
And your water map would be:

```
UCSB$waterpoly
```

A simple example can be seen on this [page](https://mikejohnson51.github.io/AOI/articles/useCases.html) under 'Rayshader'. Generally the site is 'under construction' and need to be cleaned up a bit. 

Is there a place youd like for me (or you -either or) to post an example?

**Comment by mikejohnson51** [comment]
Working Example

```r
##devtools::install_github("tylermorganwall/rayshader")
##devtools::install_github("mikejohnson51/AOI")
##devtools::install_github("mikejohnson/HydroData")

library(rayshader)
library(HydroData)
library(raster)

AOI = getAOI(list("University of Oregon", 5, 10)) %>% findNED() %>% findWaterPoly()

ned = matrix(raster::extract(AOI$NED,raster::extent(AOI$NED),buffer=1000),
             nrow=ncol(AOI$NED),ncol=nrow(AOI$NED))

pts = rasterToPoints(AOI$NED, spatial = TRUE)

mat = over(pts, AOI$waterPoly) # SLOW :(

water = matrix(mat, nrow=ncol(AOI$NED),ncol=nrow(AOI$NED))

water1 = apply(water, 2, rev)
water2 = apply(t(water1),2,rev)
water2 = apply(t(water2),2,rev)

ned %>%
  sphere_shade(texture = "imhof1", remove_edges = FALSE) %>%
  add_water(detect_water(ned, remove_edges = FALSE), color="desert") %>%
  add_water(water2, color="desert") %>% 
  #add_shadow(ray_shade(ned, remove_edges = FALSE)) %>%
  #add_shadow(ambient_shade(ned, remove_edges = FALSE)) %>%
  plot_map()

```
