### ISSUE TITLE
annotate the output of plot_gg() with render_label

### ISSUE THREAD

**Issue by benjaminschwetz** [tylermorganwall/rayshader#82]
I am trying to wrap my head around how I could annotate a 3D plot from a ggplot object in a similar way to `ggplot2::geom_label`. From the README it seems that `render_label` could do the trick but it requires a `heightmap` object like `montereybay`, which I don't have.

Is there another way to combine this with `plot_gg` output, or is there a plan to add such a functionality?

**Comment by tylermorganwall** [comment]
You can currently output the height matrix for the 3D ggplot by typing `save_height_matrix = TRUE` in `plot_gg()` and use that as the height matrix for the `render_label()` function.

**Comment by NikdAK** [comment]
Sorry to open this issue again, but I am having problems understanding the annotation in a basic plot. 

I have this very simple example and would like to annotate some point in the center peak (or any chosen position).

```
dat <- data.table(rnorm(100), rnorm(100))
ptest <- ggplot(dat, aes(V1, V1)) + stat_density_2d(aes(fill = stat(nlevel)), geom = "polygon", n = 200, bins = 50, contour = TRUE)
heightmat <- plot_gg(ptest,multicore = TRUE,width=5,height=5,scale=250,windowsize=c(1400,866),zoom = 0.55, phi = 30, save_height_matrix=T)
render_label(heightmat,lat = 0, long = 0, text = "Test") 
```

But this does not to do anything. How would a proper approach look like?
Thank you very much.
