### ISSUE TITLE
render_highquality() returns "could not find function 'diffuse'"

### ISSUE THREAD

**Issue by ttuff** [tylermorganwall/rayshader#84]
> elmat %>%
+     sphere_shade(zscale = 10, texture = "imhof1") %>%
+     plot_3d(montereybay, zscale = 50, fov = 0, theta = -15, phi = 45, 
+             windowsize = c(1000, 800), zoom = 0.3,
+             water = TRUE, waterdepth = 0, wateralpha = 0.5, watercolor = "lightblue",
+             waterlinecolor = "white", waterlinealpha = 0.5, baseshape = "circle")
                                                                                                       
> Sys.sleep(0.2)
> render_highquality()
Error in diffuse() : could not find function "diffuse"

**Comment by tylermorganwall** [comment]
Install the latest version of rayrender from github:

remotes::install_github("tylermorganwall/rayrender")

**Comment by ttuff** [comment]
There is goes! Thanks!
<img width="358" alt="screen-capture-1" src="https://user-images.githubusercontent.com/19940116/68507096-2081f280-0239-11ea-886f-448c20a3845a.png">
