### ISSUE TITLE
could not find function "render_highquality" on Windows OS

### ISSUE THREAD

**Issue by bayoishola20** [tylermorganwall/rayshader#85]
```
Error in render_highquality(lightdirection = 0, lightaltitude = 30, clamp_value = 10,  : 
  could not find function "render_highquality"
```

**Comment by tylermorganwall** [comment]
Uninstall and reinstall the package from github:

```r
remove.packages("rayshader")
remotes::install_github("rayshader")
remotes::install_github("rayrender")
```

**Comment by bayoishola20** [comment]
Thank you! That resolved the missing "render_highquality" function but another pops when ran.

`Error in diffuse() : could not find function "diffuse"`

**Comment by tylermorganwall** [comment]
No need, just uninstall rayrender and reinstall the github version:

```r
remove.packages("rayrender")
remotes::install_github("tylermorganwall/rayrender")
```

Also restart R

**Comment by bayoishola20** [comment]
That has now been resolved but yet another shows up.

```
Error in .Call(`_rayrender_render_scene_rcpp`, nx, ny, ns, fov, ambient_light,  : 
  Incorrect number of arguments (63), expecting 62 for '_rayrender_render_scene_rcpp'
```

Code used:

```
render_highquality(lightdirection = 0, lightaltitude  = 30, clamp_value = 10, 
                   samples=200, clear=TRUE)
```

**Comment by tylermorganwall** [comment]
The issue is the package isn't fully uninstalling--try uninstalling rayrender, restarting R, and installing it from github again. If that doesn't work, you'll need to go into the folder containing your packages (found by typing `.libPaths()`) and delete the rayrender folder.

**Comment by bayoishola20** [comment]
Thank you! This does resolve the issue(s).


PS: Just incase someone has same issue, removing rayshader didn't happen until I navigated to
`C:\Users\{Your_Computer_Name}\Documents\R\win-library\3.6` and manually deleted the folder `00LOCK-rayshader`

**Comment by tylermorganwall** [comment]
Great!
