### ISSUE TITLE
library(rayshader) hangs

### ISSUE THREAD

**Issue by traversc** [tylermorganwall/rayshader#87]
Using R 3.5.3 on Mac OS.  `library(rayshader)` hangs and doesn't complete, there is no error message.  Could you help me out?

**Comment by tylermorganwall** [comment]
Not enough information to help me here--can you type `sessionInfo()` and post the output? Also, I recommend installing from CRAN over the github repo, and installing the newer version of R if you can (3.6.x).

**Comment by traversc** [comment]
I re-ran the following:
```
sessionInfo()
install.packages("rayshader")
library(rayshader)
```

Here is the output:

```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.3 tools_3.5.3   
> install.packages("rayshader")
Installing package into ‘/Users/tching/Library/R/3.5/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/rayshader_0.13.1.tgz'
Content type 'application/x-gzip' length 1697056 bytes (1.6 MB)
==================================================
downloaded 1.6 MB


The downloaded binary packages are in
	/var/folders/w9/n1w04yfs0j3fj5ftrq9vxn5nj6m7h0/T//RtmpvxQH98/downloaded_packages
> library(rayshader)
((nothing happens here))
```

Do you think updating to 3.6 would help?

**Comment by tylermorganwall** [comment]
Before updating, try going to `/Users/tching/Library/R/3.5/library` and deleting the rayshader library, and try installing it again.

**Comment by traversc** [comment]
Didn't help.  I'll give updating R a shot and will let you know.

**Comment by elbaws** [comment]
I'm experiencing the same issue. Tried installing from `install.packages("rayshader")` and `devtools::install_github("tylermorganwall/rayshader")` and removing the package from `/Library/Frameworks/R.framework/Versions/3.6/Resources/library/` several times. But as soon as I try to load the package using `library(rayshader)` R hangs and becomes unresponsive until I force quit and restart it.

```
sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.2 tools_3.6.2
```

**Comment by tylermorganwall** [comment]
Try installing all the packages listed in the "imports" section of the rayshader CRAN package page and try again.

https://cran.r-project.org/web/packages/rayshader/index.html

**Comment by elbaws** [comment]
I installed those packages and updated the ones I already had installed. Now when I try to load them individually it seems that R hangs on the package `rgl`.

**Comment by elbaws** [comment]
I installed XQuartz again from here: `https://www.xquartz.org`. Then installed `rgl 0.100.30` from source. Can now load both rgl and rayshader, so this issue is solved for me..

**Comment by tylermorganwall** [comment]
@traversc  See if this solution fixes your problem as well.

**Comment by tylermorganwall** [comment]
Closing, if you still have issues after trying the above, comment in this closed issue.
