### ISSUE TITLE
Suggestion: high relief in plot_gg's text

### ISSUE THREAD

**Issue by mateuspestana** [tylermorganwall/rayshader#88]
I was wondering about 3d printing some graphs so blind people could "feel the data", but the text on plots (labels, axis text, title...) won't pass to the .stl file. So, this is my suggestion: is  there any possibility of giving the text some relief so we could print the complete graph? Maybe even changing  the font to Braille and making it in relief,  so it's perfect for blind people. 

Any other ideas?

**Comment by tylermorganwall** [comment]
So I've toyed with this idea myself ([see my blog post on 3D printing with rayshader](https://www.tylermw.com/3d-printing-rayshader/)): 

![brailleplotweb](https://user-images.githubusercontent.com/297609/71291057-77521000-233f-11ea-99ea-5292e453b762.jpg)

However, I don't believe most computers have a built-in font for braille, so it's not really possible to build into rayshader. Right now I'm sticking with only data mapping to height, but I might add some additional options for adding, let's say, axes or ticks to relief as well. But I don't expect those features to come anytime soon.

**Comment by ArturLourenco** [comment]
Hi Tyles, me again. Any news about this feature?

**Comment by tylermorganwall** [comment]
As promised (particularly the "not anytime soon part"☺️), this has been added in the latest version (4751ab2665fb007719f45982d84be6f5b0b1bbb3).
