### ISSUE TITLE
'Generic' Tree/Forest Rendering

### ISSUE THREAD

**Issue by simon-tarr** [tylermorganwall/rayshader#89]
Hello,

Firstly - thanks so much for your time in developing this package. I think I'm going to be a heavy user of this package over the coming months and years!

This is a general question rather than an issue/feature request. I was wondering how easy it would be to simulate trees/woodland/forest using `rayshader`? I am an ecologist working with bats and I'm looking at ways of representing the locations of bat roosts in individual trees across a landscape. I have a DEM of my area of extent and point data of the location of individual trees important to the study. It would be good if I could add a generic tree (or even a simple cone) on the landscape at these points to represent each roost. I can then label these features with the built-in annotation functionality.

Many thanks,
Simon

**Comment by tylermorganwall** [comment]
Possible, especially if it's just a simple cone. I'll look into adding a feature similar to render_label() to place trees.

**Comment by simon-tarr** [comment]
That's great, thank you! Looking forward to testing for you in due course.

**Comment by tylermorganwall** [comment]
Feature added in 151dfd69e7313646424005dcf9ce5222d0ebbe24
