### ISSUE TITLE
Problem with render_highquality to overlay 3d figure

### ISSUE THREAD

**Issue by andylin1995** [tylermorganwall/rayshader#90]
Hi I just overlay my topography data with an ice sheet by calling plot_3d again and its works perfectly in the interactive interface like this:

![image](https://user-images.githubusercontent.com/42965663/70001408-2677a480-1555-11ea-81e7-ef6fb6fb973f.png)

However, when I use the render_highquality function, it gives me something like this: 

![image](https://user-images.githubusercontent.com/42965663/70001487-59ba3380-1555-11ea-8f57-8b7c04924ab7.png)

It seems like I missed the background, so what should I do to solve this?

**Comment by tylermorganwall** [comment]
There are two issues here: first, it looks like the ice sheet layer is sliced out using NA entries in non-ice regions, and currently `render_highquality()` only supports rectangular 3D plots. Secondly, `render_highquality()` is currently designed only to try and pull out a single 3D figure, so the "multiple calls to plot_3d()" method won't work for this purpose.

You can work around this, however: Replace the NA's in the ice sheet layer with the the same `soliddepth` value as used in the underlying terrain 3D plot (to make the plot rectangular), and then save each object to a 3D model using the `save_obj()` function. You can then use the `rayrender` package to combine the two manually:

```r
soliddepthval = -200 #Or some other value
plot_3d(underlying_terrain, hillshade, soliddepth = soliddepthval) 
save_obj("terrain.obj")
rgl::rgl.close()

ice_sheet[is.na(ice_sheet)] = soliddepthval 
plot_3d(ice_sheet, ice_hillshade, soliddepth = soliddepthval)
save_obj("ice.obj")
rgl::rgl.close()

#Update to the latest version of rayrender
remotes::install_github("tylermorganwall/rayrender")
library(rayrender)

lightaltitude = 45
lightdirection = 315

xz_rect(xwidth=10000, zwidth=10000, y=-200) %>%
  add_object(obj_model("terrain.obj", texture=TRUE)) %>%
  add_object(obj_model("ice.obj", texture=TRUE)) %>%
  add_object(sphere(x=1000 * cospi(lightaltitude/180) *sinpi(lightdirection /180),
                    y=1000  * sinpi(lightaltitude/180),
                    z=-1000 * cospi(lightaltitude/180) * cospi(lightdirection /180), 
                    radius=100,
                    material = light(color = "white", intensity= 800))) %>%
  render_scene(parallel=TRUE, lookfrom = c(1000,1000,1000))

```

This still requires a bit of manual adjustment (the light specified in the sphere call will need to be adjusted in position/light intensity/size, as will possibly the y-position of the xz_rect() and the `lookfrom` argument), but it's a solution until I get `render_highquality()` to support NA values.

**Comment by andylin1995** [comment]
> There are two issues here: first, it looks like the ice sheet layer is sliced out using NA entries in non-ice regions, and currently `render_highquality()` only supports rectangular 3D plots. Secondly, `render_highquality()` is currently designed only to try and pull out a single 3D figure, so the "multiple calls to plot_3d()" method won't work for this purpose.
> 
> You can work around this, however: Replace the NA's in the ice sheet layer with the the same `soliddepth` value as used in the underlying terrain 3D plot (to make the plot rectangular), and then save each object to a 3D model using the `save_obj()` function. You can then use the `rayrender` package to combine the two manually:
> 
> ```r
> soliddepthval = -200 #Or some other value
> plot_3d(underlying_terrain, hillshade, soliddepth = soliddepthval) 
> save_obj("terrain.obj")
> rgl::rgl.close()
> 
> ice_sheet[is.na(ice_sheet)] = soliddepthval 
> plot_3d(ice_sheet, ice_hillshade, soliddepth = soliddepthval)
> save_obj("ice.obj")
> rgl::rgl.close()
> 
> #Update to the latest version of rayrender
> remotes::install_github("tylermorganwall/rayrender")
> library(rayrender)
> 
> lightaltitude = 45
> lightdirection = 315
> 
> xz_rect(xwidth=10000, zwidth=10000, y=-200) %>%
>   add_object(obj_model("terrain.obj", texture=TRUE)) %>%
>   add_object(obj_model("ice.obj", texture=TRUE)) %>%
>   add_object(sphere(x=1000 * cospi(lightaltitude/180) *sinpi(lightdirection /180),
>                     y=1000  * sinpi(lightaltitude/180),
>                     z=-1000 * cospi(lightaltitude/180) * cospi(lightdirection /180), 
>                     radius=100,
>                     material = light(color = "white", intensity= 800))) %>%
>   render_scene(parallel=TRUE, lookfrom = c(1000,1000,1000))
> ```
> 
> This still requires a bit of manual adjustment (the light specified in the sphere call will need to be adjusted in position/light intensity/size, as will possibly the y-position of the xz_rect() and the `lookfrom` argument), but it's a solution until I get `render_highquality()` to support NA values.


Many thanks for this, I've managed to make it work, and just need to adjust some parameters to make it looking better. Great solution!

![image](https://user-images.githubusercontent.com/42965663/70006125-e66bee00-1563-11ea-9c9d-cd45f330c86b.png)
