### ISSUE TITLE
could not find function "light": render_highquality

### ISSUE THREAD

**Issue by ctlamb** [tylermorganwall/rayshader#95]
Not sure whats going on here, I have new version of rayshader installed, 0.13.7. If I do light=FALSE it runs, but output is black. Any thoughts?

`render_highquality(filename=here::here("plots", "lambda.png"))
Error in light(color = lightcolortemp, intensity = lightintensitytemp) : 
  could not find function "light"`

**Comment by tylermorganwall** [comment]
Try updating rayrender to the latest version and try again:

```r

remotes::install_github("tylermorganwall/rayrender")

```

**Comment by tylermorganwall** [comment]
Should be fixed and the latest version of rayrender is now on the CRAN
