### ISSUE TITLE
library(rayshader) never loads on MacOS

### ISSUE THREAD

**Issue by paulditterline** [tylermorganwall/rayshader#97]
Installed both the CRAN and GitHub version. Session info:

```
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.2 tools_3.6.2   
```

When I run `library(rayshader)`, it just hangs forever. I've let it run 10 minutes, eventually just freezes my MacBook Pro. I've installed XQuartz and restarted as well. 

Updated to Catalina tonight, but same issue was on Mojave.

**Comment by tylermorganwall** [comment]
Does it hang when you load the `rgl` package? Try loading the dependencies one by one and see if one of those is causing the issue.

**Comment by intertwine** [comment]
I was able to get rayshader to load successfully (R version 4.0 (CRAN); Mac OS Catalina, Beta, 10.15.5) by installing XQuartz from from xquartz.org.

**Comment by paulditterline** [comment]
Looks like `rgl` may be the issue. After `install.packages(rgl)`, `library(rgl)` just hangs.

**Comment by tylermorganwall** [comment]
Closing due to this being an `rgl` issue.

**Comment by paulditterline** [comment]
Happy Thanksgiving!

**Comment by wilrogers** [comment]
Hey all, did anyone ever find a fix to this? I have the same issue after updating my computer, R, RStudio, all packages, XCode etc. I posted this question to the rgl repo https://github.com/dmurdoch/rgl/issues/11. Thanks!
