### ISSUE TITLE
Feature Request: Documentation on linux dependencies

### ISSUE THREAD

**Issue by ababaian** [tylermorganwall/rayshader#98]
Just installed rayshader and it's working great, thanks.

I did have to do a little bit of searching to get two dependencies installed. I have a vanilla `Ubuntu 18.04 LTS` system, there were two dependency packages that couldn't install due to missing libraries.

Can I suggest adding the following dependencies to the documentation?
- `libtiff-dev`
- `libgdal-dev`

or 
```
sudo apt-get update
sudo apt-get install libtiff-dev
sudo apt-get install libgdal-dev
```

**Comment by tylermorganwall** [comment]
Added in 4c103d265836eedb958091cefda38c9884ed908f
